### ISSUE TITLE
Fall Semester (2017) Schedule Planning

### ISSUE THREAD

**Issue by Serubin** [RITlug/tasks#1]
Week | Day | Title | Brief | Workshop | Owner
-- | -- | -- | -- | -- | --
01 | Sept. 01 | RITlug Introduction | Intro to what the club is about and who the leaders are | n/a | @TaylorBowling @Serubin
02 | Sept. 08 | Linux 101 | Intro to what Linux is and why we use it |  | @axk4545 @TaylorBowling 
03 | Sept. 15 | Open Source 101 | What is open source? What does it all mean and how can I get involved? A quick dive into the root of open source, finding a community, and how to get involved. |  | @jflory7 
04 | Sept. 22 | (Workshop) Build your own virtual reality experience in an hour! | Join RITlug to build your own virtual reality experience in less than an hour! [Christos Bacharakis](https://bacharakis.com/), a project manager from [Mozilla](https://www.mozilla.org/en-US/), is joining RITlug all the way from Greece to dive into the virtual reality world and more with [A-Frame](https://aframe.io/). Practice your git and HTML skills by building an amazing cross-platform VR experience for you to share with your friends. Yes, it’s that easy! | Interactive workshop with [A-Frame](https://aframe.io/)  | @bacharakis 
05 | Sept. 29 | (Talk) Encrypt ALL the things with LetsEncrypt | Are you dreams haunted by a world without encryption? Do you envision a world of madness without HTTPS? RITlug has the answer to put away your nightmares. Learn how to encrypt ALL the things with free SSL/TLS certificates from LetsEncrypt! Learn what LetsEncrypt is all about and how you can use it to generate your own certificates for free. |  | @jflory7 
06 | Oct. 06 | (Talk) In-Depth: Backups @ RITlug | (Talk/Discussion) Learn how RITlug protects its infrastructure and about general best practices for handling your own backups.  |  | @Serubin
07 | Oct. 13 | (Talk) Building A Minecraft Server with Spigot  | (Talk / part Workshop) Learn more about SpigotMC, the open source Minecraft server software that lets you build your own Minecraft server and extend it beyond what the developers ever imagined. We’ll create a server and how to customize it your liking. |  | @jflory7
08 | Oct. 20 | (Talk) Women in Open Source | Last May, Red Hat and the open source community honored two exceptional women, Avni Khatri and Jigyasa Grover for the "Women in Open Source" award. This week, the RIT Linux User's Group (RITlug) looks into the history behind the role of women in open source and tech communities. We examine the invaluable and extraordinary accomplishments of pioneering women that changed the foundations of open source and are paving the way for future generations of women to do the same.  |  | @fosspotato 
09 | Oct. 27 | (Workshop) Hacktoberfest Hackathon | Want to get a free t-shirt and stickers from DigitalOcean and GitHub? Make four contributions to projects on GitHub and get free swag! During the two hours, we'll help you get in your contributions before October comes to an end. Bring a laptop! |  | @jflory7
10 | Nov.  03 | (Talk) Overview of Distributed Computing | Get an introduction to distributed computing, such as virtualization and containers, how we use them, and why. |  | @ct-martin
11 | Nov.  10 | (Talk) Freedom From State: An Intro to Haskell | Haskell is a purely functional programming language, much different than C or Java. But what is purity, and why does it matter? What does Haskell actually offer for building software? And what in the world is a monad? Learn how Haskell can change the way you think about programming. We'll cover some syntax, a handful of demos, and discuss how Haskell's concepts apply to software development! |  | @Josh1147582
12 | Nov.  17 | (Workshop) Spy Pi workshop | Spy Pi is a simple DIY project you can make with a Raspberry Pi. Outfit any old picture frame with a Raspberry Pi and webcam, and suddenly intruders will never know what's coming! We'll walk through the assembly, configuration, and installation so you can go home and make your own. |  | @TaylorBowling 
13 | Nov.  24 | (_Thanksgiving, no RITlug_) | (_Thanksgiving, no RITlug_) | (_Thanksgiving, no RITlug_) | (_Thanksgiving, no RITlug_)
14 | Dec. 01 | (Talk) Linux and FOSS: Hidden in the Data Center | It used to be that data centers were ruled by big iron and proprietary software. Today data centers are running on top of Open Source. In many cases the Open Source stack is hidden. This talk will highlight several vendors that leverage Open Source in their products. |  | @cprofitt 
15 | Dec.  08 |  |  |  |

**Comment by Serubin** [comment]
@jflory7 @axk4545 @TaylorBowling @fosspotato

I want to kick off the planning publicly as we start to really map out this semester.

**Comment by Serubin** [comment]
# Detailed Tasking

## Linux 101 1 (9/1) 
Tasked too: @axk4545 @TaylorBowling. Hard deadline: **8/25**

**Comment by jflory7** [comment]
@Serubin If I remember right, our current plan is for @TaylorBowling to lead with @Serubin supporting the creation of a general RITlug intro presentation, followed by Open Source 101 (@jflory7) and then Linux 101 with @TaylorBowling and @axk4545 together, right?

**Comment by TaylorBowling** [comment]
I've updated the schedule above based on recent decisions. I'll start working on the RITlug introduction slideshow next week, if anyone has anything they'd like to add or would like to further collaborate please let me know!

**Comment by jflory7** [comment]
@TaylorBowling Thanks. As an FYI too, if you want a gap week by swapping the _Linux 101_ and _Open Source 101_ sessions, we can do that if you think you'll need the time. Otherwise, I'll use the extra week to try to come up some marketing or try to promote it a bit outside of GCCIS.

As a general note, I'd like to give quick sessions on Docker / containers and also Kubernetes (quick is the emphasis, I have enough knowledge to be dangerous but not be represent the entire Kubernetes stack). I imagine this being in the October time frame, but I'll need to sit down and map out a topic and what I want to cover. In particular, I want to use the planning outline that was developed at the Mozilla all-hands event last weekend.

I'll also see if we can fill some of these weeks with guest presenters.

**Comment by patkub** [comment]
I'd like to give a quick session on [Polymer](https://www.polymer-project.org/) web components and Progressive Web Apps (PWAs), and web testing in a CI.

**Comment by Serubin** [comment]
@patkub Could you swing it early october? I'd love to see this happen!
Week 7, Oct. 13?

**Comment by patkub** [comment]
@Serubin Ok, I can do Oct. 13.

**Comment by Serubin** [comment]
@fosspotato How's Oct. 20th for your presentation.

**Comment by Serubin** [comment]
Adding @fosspotato's presentation

**Comment by jflory7** [comment]
Updated table with @bacharakis's presentation, pushed some things around.

**Comment by jflory7** [comment]
@patkub I pinged you in Telegram but didn't get an answer – are you still good for this Friday?

**Comment by ct-martin** [comment]
Propsed talks:
- Ansible (???, Flory has a name in mind)
- Overview of Distributed Computing (Me)
- Virtualization (@Serubin ?)
- Docker+Kubernetes (Flory)

(Cc @jflory7)

**Comment by jflory7** [comment]
Updated Week 07 with Spigot talk. Reminder that @fosspotato is up for next week with "Women in FOSS".

**Comment by jflory7** [comment]
@ct-martin volunteered to give "Overview of Distributed Computing" on Nov. 3rd. We might try to make November the "month of the cloud" if I can get my Kubernetes talk done in time or if we can get a guest speaker for an Ansible one.

Oct. 27th is currently blank, but I was thinking we could make that into a [Hacktoberfest](https://hacktoberfest.digitalocean.com/) Friday for club members to work on open source projects to get their free t-shirt and stickers from DigitalOcean.

**Comment by jflory7** [comment]
## Oct. 27th

* **Hacktoberfest Hackathon**: Want to get a free t-shirt and stickers from DigitalOcean and GitHub? Make four contributions to projects on GitHub and get free swag! During the two hours, we'll help you get in your contributions before October comes to an end. Bring a laptop!
* **Organized by**: @jflory7

## Nov. 3rd

* **Overview of Distributed Computing**
* **Organized by**: @ct-martin 

@ct-martin Please provide a 2-3 sentence description of your talk we can use to promote your session.

## Nov. 10th

* **Freedom From State: An Intro to Haskell**: Haskell is a purely functional programming language, much different than C or Java. But what is purity, and why does it matter? What does Haskell actually offer for building software? And what in the world is a monad? Learn how Haskell can change the way you think about programming. We'll cover some syntax, a handful of demos, and discuss how Haskell's concepts apply to software development!
* **Organized by**: @Josh1147582

**Comment by cprofitt** [comment]
I will do a talk on December 1st.
**Linux and FOSS: Hidden in the Data Center**
It used to be that data centers were ruled by big iron and proprietary software. Today data centers are running on top of Open Source. In many cases the Open Source stack is hidden. This talk will highlight several vendors that leverage Open Source in their products.

**Comment by jflory7** [comment]
That's a wrap for this semester! We'll pick up with planning for next semester over the winter break.
