### ISSUE TITLE
Grant admin access to jwflory for Teleirc

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#100]
When my permissions were downgraded in the RITlug org, I lost access to the Teleirc repository. Could I be re-added as an administrator to the repository?

**Comment by ct-martin** [comment]
Gave @jwflory maintainer rights to the Teleirc team and created a new Teleirc Admins sub-team with @jwflory in it and admin access to the repo, like TigerOS has.

@jwflory you'll need to add other admins to the sub-team yourself.
