### ISSUE TITLE
Eboard Meeting Time (Spring 2019)

### ISSUE THREAD

**Issue by jrtechs** [RITlug/tasks#101]
# When
For the spring semester we need to determine when is a good time for Eboard meetings and where we are going to have eboard meetings. The caveat of this issue is that we should also consider about the meeting times of the committees #99.

### Poll
[When is good poll](http://whenisgood.net/fnrbqmz)
### Results
[When is good results](http://whenisgood.net/fnrbqmz/results/brc4ify)

# Where
In the past we have held meetings in the library and GSSIS, however, I think it would be nice to hold them Magic this semester. I checked reserve.rit.edu and the room which we use for FOSS hours (3190) is listed but, is limited to Magic faculty. We can probably get SJ to reserve us space if desired.

**Comment by icflournoy** [comment]
### Eboard Meeting Notes 2019-01-17

Book a small conference room in the MAGIC Center for eboard meeting for the Thursday 3:30 - 4:30 time slot. @Tjzabel will email SJ to coordinate the reservation.
