### ISSUE TITLE
Renew `ritlug.club`

### ISSUE THREAD

**Issue by ct-martin** [RITlug/tasks#103]
We need an EAF to renew this, will not cost much. Will expire Jan. 28

**Comment by ct-martin** [comment]
Domain expires Jan. 28

**Comment by Tjzabel** [comment]
@jibby0 I think 4 years should be perfectly fine.

**Comment by jibby0** [comment]
Alright, I'll order 4 years for each.

**Comment by Tjzabel** [comment]
What's our current status with this? Afaik, the domain ended tonight, the 28th. Is our current plan to wait for the grace period while we try to get the EAF situated?

**Comment by jibby0** [comment]
Yup, I can't get a signature for the EAF until tomorrow. So it'll have to wait. If all goes well, we'll have the domain renewed by tomorrow afternoon.

**Comment by Tjzabel** [comment]
@jibby0 where do we stand with this?

**Comment by jibby0** [comment]
@Tjzabel Still working on getting SJ's signature for the EAF. A series of unfortunate events (polar vortex, personal issues, etc.) prevented that last week.

I'm unavailable to do it today, hoping to catch him at FOSS hours tomorrow.

The grace period on expired domains is still active for a while, but I don't want to hold up deployment of the r900.

**Comment by jibby0** [comment]
Payments made, RIT VISA returned. Namecheap shows both ritlug.com and ritlug.club are good until 2023.

Receipts are in the RITLUG Google Drive, under Finance.

I think we can close this up. :+1:
