### ISSUE TITLE
Imagine RIT 2019

### ISSUE THREAD

**Issue by jrtechs** [RITlug/tasks#106]
We should start considering what we are going to present so that we can submit the proposal by these dates. 

http://www.rit.edu/imagine/proposal.php

Important Deadlines
February 9, 2018 to be considered for placement in the Gordon Field House
March 20, 2018 to be included in the print program
April 6, 2018 to complete and confirm Exhibitor Profiles

**Comment by Tjzabel** [comment]
Since we are usually never in the Gordon field house, I think it's safe to set a due date for this for March 20th, and not Feb 09.

**Comment by icflournoy** [comment]
Projects:
- TigerOS
- Magic Mirror
- Floppy Drives
- Dual touchscreen laptops @ct-martin needs to do some work before committing
- CBET Monitoring
- NLP analyze domain names @jibby0 
- Grafana dashboard for ceph? (@ct-martin @icflournoy can help with grafana dashboarding)

**Comment by Tjzabel** [comment]
## Next Steps
In order to move forward with making a proposal, we need to figure out how we want to *describe* our exhibit.

Below is a very rough draft of what to write.

```
The RIT Linux Users Group (RITlug) is a student-led organization to promote and teach students about Linux & open source.

This exhibit will be demonstrating projects based around, or using, Linux as its operating system. 
```

**Comment by ct-martin** [comment]
At a previous planning meeting we discussed using "to contribute to and
engage students in" instead of "promote and teach" as it sounds more
inclusive and less talk-oriented. This would be a good time to roll out the
change and update the website; it's been on my list for a while but I never
got around to it.

Also, h/t to @jrtechs for the new language

--
Christian Martin (Phone)

**Comment by Tjzabel** [comment]
## Update
RITlug proposal has been successfully submitted.

## Next Steps
In order to complete our full proposal, we need to complete:
* Exhibit Information (March 19)
* Service Requests (March 19)
* Add Exhibitors (April 5)
* Photos and Images

**Comment by Tjzabel** [comment]
## Update
Exhibit Information, and Service Requests sections have been completed.

Next steps are to add exhibitors.

**Comment by jrtechs** [comment]
The current plan is to form a schedule for our booth by the end of this Friday

**Comment by jrtechs** [comment]
# Eboard Meeting 4-18-19

## Stuff to bring

### @Tjzabel 
- Banner
- Monitor
- Spare laptop -- tigeros
- power cables for laptop/monitor
- Magic Mirror
- Sticker

### @jrtechs 
- Floppy Drives
- Laptop -- to control floppy project
- Spare USB keyboard and wireless mouse

### @ct-martin 
- Spare Laptop -- for cbet monitoring

### @jibby0 
- Power Strip

**Comment by jrtechs** [comment]
I will be picking up the T-shirts and meal cards for the entire club next week. We will distribute the shirts and meal cards at next weeks meeting (April 19).

**Comment by jrtechs** [comment]
@RITlug/eboard-2018-2019 Shirts are picked up and are now in my office. I will pass these out at the meeting on Friday (4-26)

**Comment by Tjzabel** [comment]
ImagineRIT has concluded! Thanks everyone!
