### ISSUE TITLE
Replace current backup solution for Titan & New servers

### ISSUE THREAD

**Issue by Serubin** [RITlug/tasks#107]
Replace current backup solution for Titan & New servers. The current backup solution is being paid in full by Serubin. By April 1st I'm requesting that we switch to a RITLUG funded solution.

Currently the backup solution uses Online.net's C14 archival storage solution at $0.01 per GB / Month with no transaction costs (archive/unarchive). 

Another solution is amazon glacier which is $0.004 per GB / Month and unarchive @ $0.01 per GB

**Comment by jibby0** [comment]
Ayyyyooo. :wave: So eboard is still figuring out if/how we'd like to do offsite storage, and what items will be important enough to back up. However, there are some essential things we can take care of in the meantime: with your approval, we would like to

- Modify the current backup solution on Titan to exclude any RITLUG VMs and data. 
- Remove any RITLUG data from Titan's existing offsite backups. Or make a list of what's ours, so you can remove it yourself (I'm not sure who has access to those).
- Add a script to periodically backup RITLUG data on Titan to RITLUG infrastructure on campus (the R900 or something). Our idea is to gather all this data and then offsite it with our own backup solution, or at least colocate it across campus.

Does this sound alright? Any suggestions or recommendations?

**Comment by Tjzabel** [comment]
@jibby0 sounds good for the most part.

*If possible*, it would definitely be great if we could simply back up Titan to the R900 instead of having to incur backup costs. 
This method, however, is blocked on us completing the R900 setup.

**Comment by Tjzabel** [comment]
@serubin does what @jibby0 sound good for a plan?

**Comment by Serubin** [comment]
I have no issues any of this. I've removed all of RITLUG's stuff from the backups as of early November due to the personal costs associated to storing that. 

If you guys intend to do full vm snapshots I can accomidate with some shell access to Titan. Otherwise you should be good to add your backup scripts to the VMs you want to backup.

**Comment by ct-martin** [comment]
The R900 is online since Thursday; need access to Titan to set up backups for the VMs we care about (e.g., we don't care about the TigerOS Builder but do care about the IRC and GitLab servers). I'm going to use Proxmox's built-in backup thing for simplicity and have a share for Titan on the R900.

**Comment by ct-martin** [comment]
Also, I'm going to do snapshot backups since I don't have access to all of our VMs

**Comment by Serubin** [comment]
You may need additional privileges for proxmox's backup tools. Let me know if that's the case.

**Comment by jzaia18** [comment]
We will consider backing up to Jeffery's off-campus server in the short term until backups can go onto the R900. Hopefully more information will be known by next meeting.

**Comment by Tjzabel** [comment]
We decided we have no reason to back up any data hosted on Titan.
