### ISSUE TITLE
Finalize Teleirc meeting time and place

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/tasks#108]
@jwflory sent out a whenisgood poll to find a meeting time that fits best with everyone's schedules.

I believe a time has been finalized. We now need to send out that meeting time, and get to work on a room reservation somewhere.

**Comment by jwflory** [comment]
The meeting time is set in place, but a consistent, recurring meeting place still needs to be reserved. Help from current eboard to do this is needed, if I recall correctly.

**Comment by Tjzabel** [comment]
@jwflory is there something specific eboard can help out with in regards to getting a meeting room?

**Comment by jwflory** [comment]
@Tjzabel We need a recurring meeting location until 20 April 2019. I am unable to book recurring reservations.

**Comment by jwflory** [comment]
We have a recurring reservation in MSS-3190 for the rest of the semester. Thanks @Tjzabel @ct-martin for helping figure this out! This issue can be closed. :clapper:

**Comment by Tjzabel** [comment]
@jwflory :tada: :tada:
