### ISSUE TITLE
Find TigerOS meeting time and place

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/tasks#109]
The TigerOS SIG needs to find a proper meeting time and place this semester.

## Action Items
* Find meeting time -- whenisgood poll in announcements channel (@ct-martin or @Tjzabel )
* Find meeting room -- most likely in MAGIC center

**Comment by Tjzabel** [comment]
@ct-martin realistically, is having a weekly TigerOS meeting something that you have bandwidth for?

**Comment by ct-martin** [comment]
Not unless it's during a regular meeting or every other week

--
Christian Martin (Phone)

**Comment by Tjzabel** [comment]
We've determined it would be best to have TigerOS meetings during general meeting down-time. Weekly meetings have been unproductive in the past, and so it would be best to meet up when progress has been made.
