### ISSUE TITLE
Add poster template to runbook

### ISSUE THREAD

**Issue by jflory7** [RITlug/tasks#11]
# Summary

The poster template we are currently using (a la @TaylorBowling) needs to be added to the [RITlug Runbook](https://github.com/RITlug/runbook) to help keep it somewhere public and easy to work with later

# Explanation

This one is pretty simple, but will require @TaylorBowling to do it since he has the current poster template. I think adding a new folder to the Runbook titled `resources/` and dropping the version @TaylorBowling is working with in there would be enough.

**Comment by jflory7** [comment]
@TaylorBowling Could you drag-n-drop upload the template you're working with to this GitHub issue please?

**Comment by TaylorBowling** [comment]
@jflory7 Been holding off on this due to the recent logo redesign. We can discuss changes to the poster template, in order to update to a new format, in the next meeting, and then I will update.

**Comment by Tjzabel** [comment]
We now have our logo redesign. However, we are now currently undergoing a poster design change. Until the change is complete, we will have to wait to update the runbook.

**Comment by ct-martin** [comment]
Logo Redesign is in #28, marking this issue as blocked
