### ISSUE TITLE
Explore (and maybe order) RITlug Jackets

### ISSUE THREAD

**Issue by jibby0** [RITlug/tasks#113]
There's been some interest from club members regarding RITlug jackets.

Assuming we go with the same provider as last year, we need ~12 people to commit, for an appropriate price.

Tasks:
 - Put up a poll to gather interest in jackets
 - If enough people are interested
   - Establish a design
   - Gather orders, place order

The design and ordering process will likely be very similar to last year's.

**Comment by Tjzabel** [comment]
I can handle setting up a poll, starting the Monday we get back from break.

**Comment by Tjzabel** [comment]
I've started a poll in the RITlug announcements slack channel. I will also mention this in this week's email.

**Comment by Tjzabel** [comment]
So far we have roughly 9 individuals willing to get a jacket. 

I am going to follow up with Taylor as to how many jackets are needed, and to get a refresher as to what the due process is to complete this order.

**Comment by Tjzabel** [comment]
Deadline passed. Will pick up next semester :frowning:
