### ISSUE TITLE
Request 2019-2020 RITlug Budget

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/tasks#114]

**Comment by Tjzabel** [comment]
This is due April 30th.

**Comment by Tjzabel** [comment]
Budget request complete.

**Comment by ct-martin** [comment]
@Tjzabel are club re-recognition and locker request also done?

**Comment by Tjzabel** [comment]
@ct-martin you can comment without reopening. 

I wrote your answer in the slack channel earlier. Re-recognition is done, and lockers don't change, so there's no form for that.
