### ISSUE TITLE
Eboard Nominations for 2191 School Year

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/tasks#115]

**Comment by jrtechs** [comment]
Link to nominations:
http://cglink.me/s17020

**Comment by jrtechs** [comment]
# Eboard Notes 4-18-19

- We are going to announce the new eboard during the meeting tomorrow.
- We want the new eboard members at our next eboard meeting so we can start the on-boarding process.
- Late may we will decide when a good eboard meeting time is for the summer.

**Comment by Tjzabel** [comment]
Nominations are complete! :tada: :tada:
