### ISSUE TITLE
Work with @jwflory to set up FOSS Family Dinner EventBright

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/tasks#117]
A summary needs to be provided to @jwflory for the eventbright page. We are planning on going to Sticky Lips on Wednesday, April 24th at 5:30pm.

**Comment by Tjzabel** [comment]
> Hey all,
>
> The FOSS Family dinner is confirmed for Wednesday, December 13, 2017
> starting at 6:00pm in Sticky Lips BBQ. **Please reply (only to me) and
> confirm your attendance so I can make a reservation.**
>
> Most of you were free on Wednesday evening at 6pm. A few people were
> unable to make this time. If you have a time conflict because of an
> exam, you're welcome to join us late. The timetable is below:
>
>     http://whenisgood.net/ritfoss/dinner-dec-2017/results/tbw3mmj
>
> I chose Sticky Lips since it's close to campus. If you have dietary
> restrictions and this will not work for you, please let me know ASAP. A
> menu is here, for reference:
>
>
> http://stickylipsbbq.com/stickylips/wp-content/uploads/2017/11/stickymenufaxweb2017-v04b-nov.pdf
>
> There are two locations. We are meeting at the one at Jefferson Road,
> closest to RIT.
>
>     830 Jefferson Rd
>     Rochester, NY 14623
>     https://goo.gl/maps/nEUSqzXDGL62
>
> I'm looking forward to seeing everyone! Please let me know if you can
> make it. If you need a ride from someone to get there, please tell me as
> well, so we can figure out carpooling a little closer.
>

-- 
Cheers,
Justin W. Flory
jflory7@gmail.com

**Comment by jwflory** [comment]
The EventBrite is up now!

https://www.eventbrite.com/e/foss-family-dinner-sticky-lips-tickets-59863140264

**Comment by Tjzabel** [comment]
EventBrite is up, and email was sent out last week! Closing issue as complete :+1:
