### ISSUE TITLE
Suggested donation to Open Source Design on Open Collective

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#118]
# Summary

Suggestion to donate to [Open Source Design](https://opencollective.com/opensourcedesign) for their support in designing Teleirc logo (#116)

# Background

The good folks at @uracreative created the new Teleirc logo (uracreative/works#30) pro-bono for RITlug. The designer [suggested a donation](https://github.com/uracreative/works/issues/30#issuecomment-482794396) as a way to support their initiative and effort providing design support for open source projects.

# Details

I suggest a $50+ USD donation. However, this is up for RITlug eboard to determine how much to donate.

# Outcome

RITlug builds positive relationships and collaboration with the wider open source community

**Comment by Tjzabel** [comment]
@jwflory sounds like a great idea! 

In terms of the actual monetary funds, donating money is super tricky with club office. We may try to pursue this with the office, or I may just personally donate the money :man_shrugging:

**Comment by jwflory** [comment]
@Tjzabel I understand. From my eboard experience, I believe there is value to consistently utilize the Clubs Office-allocated budget. Demonstrating that RITlug can effectively manage and balance a budget can't hurt the club either. This is my personal POV.

**Comment by Tjzabel** [comment]
That is also true! We'll work on figuring out the best way to handle this in the upcoming week :+1:

**Comment by Tjzabel** [comment]
This will not be able to be completed before the end of this semester (with RITlug budget). We will most likely have to pick this back up in the fall if we decide to do some sort of pamphlet.

**Comment by hkeena98** [comment]
TODO: Research how to donate through the club office.

**Comment by Tjzabel** [comment]
Research has been completed on how to donate through the club office. The process consists of:
1. Submit EAF
2. Write letter of intent 


## How to write letter of intent
Letter of intent should include the following:
* Name/title of person writing letter
* Name of student club
* Club's type of activities
* Fundraising activity
* Amount collected
* Amount to be donated
* Why we chose this organization

**Comment by jwflory** [comment]
If I can help with historical context, please let me know.

I really want to see this happen since we never paid for the TeleIRC logos. The intention at the time was to skip complex invoicing for an international company based in Albania by instead [donating to Open Source Design](https://opencollective.com/opensourcedesign) via an established U.S. non-profit, Open Source Collective. The OSC is a registered 501(c)(6).

**Comment by Tjzabel** [comment]
Sadly, too much time has passed for this issue. Going to close as wontfix.
