### ISSUE TITLE
Eboard onboarding/offboarding

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/tasks#120]
## What this is
We need to figure out a time during early summer to do our onboarding/offboarding procedures.

## Changing Members

Offboarding members:
* Ian Flournoy
* Josh Bicking

Onboarding members:
* Nathaniel Larrimore
* Henry Keena

### Resources
* [Runbook onboarding/offboarding](http://runbook.ritlug.com/administration/eboard-onboarding-offboarding/)

**Comment by jrtechs** [comment]
I did all the necessary steps on-boarding/off-boarding for the github, google drive, and campus groups. 

## Things left:
- [ ] Slack -- off-boarding and on-boarding @nlMeminger 
- [ ] Git Lab Accounts and other RITlug infra
- [ ] Telegram
- [ ] IRC

**Comment by Tjzabel** [comment]
### Slack
All slack permissions should now be taken care of. 
* @nlMeminger and @hkeena98 are now Workspace Admins. 
* @icflournoy and @jibby have admin privs revolked.

### GitLab
GitLab permissions have also been updated. @nlMeminger and @hkeena98 need to create RITlug GitLab accounts in order to finish off that action item.

### Telegram
I need to reach out to @repkam to demote ian and josh.

### IRC
TBD

**Comment by Tjzabel** [comment]
@jrtechs @nlMeminger @hkeena98 do any of you guys use IRC enough to be promoted as an admin on our respective channels?

If not, I think we can mark the IRC onboarding/offboarding as complete. Me and @ct-martin are the only ones (I believe) who have admin privs there.

**Comment by hkeena98** [comment]
Hey,

Sorry, no I dont use IRC. Never have actually...

Sorry bout that one.

-Henry

**Comment by Tjzabel** [comment]
@hkeena98 all good! It's honestly not an issue. Usually in the past, everyone uses IRC, but now most folks have transferred to Matrix/Telegram. 

The last action item is for you to create a RITlug GitLab account, as we have a private credentials repo where we store all passwords related to RITlug operations.

**Comment by Tjzabel** [comment]
Everything is done!
