### ISSUE TITLE
2019 Fall Semester Room Reservation

### ISSUE THREAD

**Issue by jrtechs** [RITlug/tasks#121]
# What
We need to email a person in the IST department to get the lab reserved for RITlug for the fall semester. After that, we need to get the reservation ID and use that to get student life to register it with campus groups and EMS.

# When
Since fall class locations are not finalized yet, it is usually best to do this mid July.

# After
Finishing #49 for runbook documentation.

**Comment by Tjzabel** [comment]
We agreed we would go with the Medium DB Lab (2620) for this upcoming school year, on Fridays, from 4:30 - 6:00pm.

**Comment by jrtechs** [comment]
We have the Medium DB Lab reserved on Fridays from 4:30-6:00 PM with the IST Department. I just filled out the campus group's "Reservation Request for Non-EMS Space"; we should see these events propagated in Campus Groups in a week or two. We can close this ticket once the events are in Campus Groups.

**Comment by Tjzabel** [comment]
CampusGroups events are finally showing through :tada: :tada:
