### ISSUE TITLE
Financial Certification Test for Fall 2019

### ISSUE THREAD

**Issue by jrtechs** [RITlug/tasks#123]
During the beginning of the fall semester (August/September) all eboard members need to get financially certified. The [test](https://www.rit.edu/studentaffairs/campuslife/financial-certification-test) can be completed online and should only take a half hour. 

- [x] Jeffery R
- [x] Nathaniel L
- [x] Henry K
- [x] Tim Z

Check your name in this list after you complete the test.

**Comment by jrtechs** [comment]
As of 9-11-19, the test is still unavailable.

**Comment by jrtechs** [comment]
The test is still unavailable, I'm going to email clubs.

**Comment by Tjzabel** [comment]
I went to the club office today to get some more information on club finances. It looks like campusgroups has a [club finances link](https://campusgroups.rit.edu/clubs/student-organization-finance/) where the financial cert information is.

**Comment by Tjzabel** [comment]
@nlMeminger @hkeena98 @jrtechs have any of you guys been able to take the financial certification yet?

**Comment by jrtechs** [comment]
I'm planning on taking it sometime tonight

**Comment by hkeena98** [comment]
Ill do it sometime tonight.

**Comment by jrtechs** [comment]
Just finished, took about 8 minutes.

**Comment by nlMeminger** [comment]
Just Finished

**Comment by Tjzabel** [comment]
@nlMeminger Das ist wundebar. VIelen Dank für Ihre Zeit.

**Comment by nlMeminger** [comment]
Bitte schön

**Comment by jrtechs** [comment]
We are now all certified.
