### ISSUE TITLE
The Future is Open Conference

### ISSUE THREAD

**Issue by jrtechs** [RITlug/tasks#127]
Will Nigles from RITlug planning on doing an install fest during the conference. We should work on connecting him with Flory and SJ. We would also like to have "RITlug" do a presentation during the conference.

Current ideas:
- Tiger OS (@Tjzabel)
- running an open source club
- Using Open Source as a student

**Comment by jrtechs** [comment]
I just submitted the CFP for the student pannel.

# Abstract:
The RIT Linux Users Group (RITlug) is curating a panel of students across a range of majors to discuss how open source software is used daily by students at RIT. The panelists will be asked questions about how FOSS has influenced their coursework, CO-OPs, clubs, and personal projects while at RIT. The goal of this talk is to emphasize how students across different majors all benefit from free and open-source software. Currently speaking we have the following majors: HIC, Computational Math, CSEC, New Media Interactions and CS. Another common theme of this talk will be discussing how FOSS has created communities at RIT dedicated to helping others learn.

# Target Audience
The target audience for this submission would be anybody interested in open source software at RIT. This would be a great opportunity for prospect/current students to learn about how they can use and engage with communities on campus that use open-source software. This would also be a great chance for alums to see how open-source software has changed over time. 

# Tentative Pannel Members
- Jeffery Russell (CS)
- Henry (Human Interactive Computing/SWEN)
- Dan (Computational Math)
- Chrisitan (New Media Interactions)
- Josh N (CSEC)

**Comment by Tjzabel** [comment]
As an update to this issue on my end, the CFP for TigerOS has also been completed.

**Comment by Tjzabel** [comment]
Website for the conference is: https://fossrit.github.io/events/2019/10/26/the-future-is-open/

**Comment by jrtechs** [comment]
Talk with SJ and @jwflory to figure out when the Pannel and Tiger OS talks are scheduled so I can confirm availability with pannel members.

**Comment by jwflory** [comment]
> Talk with SJ and @jwflory to figure out when the Pannel and Tiger OS talks are scheduled so I can confirm availability with pannel members.

Rumor has it, the RITlug student panel will be between 3-4pm. A final schedule will be published (hopefully) by Friday evening.

**Comment by Tjzabel** [comment]
As an update, schedule is up, and seems to be finalized.

**Comment by jwflory** [comment]
> As an update, schedule is up, and seems to be finalized.

https://fossrit.github.io/events/2019/10/26/the-future-is-open/

**Comment by Tjzabel** [comment]
This event was a great success!
