### ISSUE TITLE
Maker Faire 2019

### ISSUE THREAD

**Issue by jrtechs** [RITlug/tasks#129]
# When 

The maker faire this year is November 23rd. 

# Application
The application to present at the maker faire is **due October 21st**.

[CFP](https://rochester.makerfaire.com/call-for-makers/application/)

# How
Over the next few weeks we will be deciding what projects we should present.

**Comment by jrtechs** [comment]
Current ideas for projects:
- Tux racer on Jeffery's Pi4
- Musical Floppy Drive Project with new music selection web interface
- Magic Mirror
- Tiger OS

**Comment by jrtechs** [comment]
I will start the application and have it done sometime Friday for people to review.

**Comment by hkeena98** [comment]
"I will bring everything." - Nathaniel

**Comment by hkeena98** [comment]
EAF Table Cloth Approved - 11/13/2019

**Comment by Tjzabel** [comment]
# Items to Bring

### Floppy Drive
* Laptop
* Floppy drives

### Tux Racer
* TV
* Spare keyboard/mouse

### TigerOS
* Monitor
* Keyboard/mouse
* Laptop running TigerOS


### Magic Mirror
* Mirror

**Comment by jrtechs** [comment]
This is a presentation with some of the logistics of the maker faire:
https://docs.google.com/presentation/d/1j-5EhWYJ3bpJcweeGXOmd6DjLefTuewEtC5vC6k3EXc/edit?usp=sharing

Currently Attending for RITlug we have:
- Jeffery
- Tim
- Russell
- Michael
- Dylan -- need to confirm

We also have 2 maybes from other upperclassmen

RITlug members presenting with FOSS
- Christian (might be ritlug?)
- Nathanial
- Justine

**Comment by Tjzabel** [comment]
Maker Faire was a success! :tada:
