### ISSUE TITLE
Organize a TigerOS Test Day

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#13]
# Summary

Organize a "Test Day" event for TigerOS to bring the general public in to get user feedback on installation and UI/UX.

# Analysis

The TigerOS team ( @axk4545 @ct-martin @Tjzabel @ReginaTL @Josh1147582 ) has a working Fedora 26 build of TigerOS. There is new focus on user interface / user experience. User feedback would be helpful for the TigerOS team to improve their documentation and consider changes to the desktop environment based on user feedback.

A TigerOS Test Day event helps promote the project and bring people in to get feedback. This is a one-day event (maybe 2-4 hours) where people could stop by and run through installation docs in a virtual machine / as a live boot and then run through various test cases the TigerOS team would prepare.

As a motivator, we can encourage people to show up to have their name added as a contributor to the project wiki and maybe in a special place in the OS.

# Implementation

1. Create installation docs for Windows / macOS users with virtual machines or doing live boots
2. Go through TigerOS tickets, highlight some where user feedback would be valuable
3. Create "test cases" with step-by-step instructions for people to run through and collect feedback
4. Create forms for people to leave feedback in (e.g. Google Drive)
5. Choose dates, begin planning with email announcement / poster design (RSVPs??)
6. Execute event, get feedback
7. Hold special meeting to analyze / figure out feedback from event

**Comment by jflory7** [comment]
@axk4545 Is this something you think we should do this semester?

* **If no**: Let's assign it to a milestone for next semester.
* **If yes**: Can you find someone on the team to help drive and plan this?

**Comment by axk4545** [comment]
@jflory7 going to check with @Josh1147582 on this. Some of it would be docs. Biggest challenge is getting useful test cases. Tentative milestone for next semester unless things change.

**Comment by axk4545** [comment]
@Josh1147582 can do the guides

**Comment by jflory7** [comment]
@axk4545 Does that mean this semester or next semester? If you can work out a specific date at the next TigerOS team meeting for this, let's get it on the calendar. When you have a specific date, drop an update in this ticket please. 😃

**Comment by Tjzabel** [comment]
@jflory7 @axk4545 sooo at this point in time, it's safe to say our TigerOS Test Day will be next semester. By that point, all of our minor issues *should* be resolved. This is something we should discuss first thing spring semester.

Thoughts?

**Comment by ct-martin** [comment]
Given that the "First Release" milestone is the end of the semester, I was
kind of assuming this would be the case


--
Christian Martin

**Comment by axk4545** [comment]
That sounds reasonable. I wish we( and me) had been a little more
productive. Hopefully FOSS project will help with that.

Aidan Kahrs
abkahrs@gmail.com

**Comment by ct-martin** [comment]
Agreed. While this is a discussion for Friday, I think it's possible to
still pull off a first release, but it may have to be for the end of break
instead of the end of the sem. If you look at the milestones, switching to
gnome is mainly  ui tweaks, while apart from doc/site stuff the first
release is the gtk thing, following up about packaging with upstream,
metapackages, and build automation.


--
Christian Martin

**Comment by jflory7** [comment]
@axk4545 @ct-martin Thanks for your feedback. I updated the tags and milestone to reflect these changes. For other discussion unrelated to the Test Day, let's move that over to the TigerOS repo or Slack.

**Comment by jwflory** [comment]
This issue recently turned one year old. I'm going to close this issue on RITlug/tasks, and the TigerOS team can take it up to organize a test day in RITlug/TigerOS. If the @RITlug/tigeros-team folks need any help from eboard to do something like this, please let us know. :slightly_smiling_face:
