### ISSUE TITLE
Order T-Shirts

### ISSUE THREAD

**Issue by jrtechs** [RITlug/tasks#131]
Order RITlug t-shirts for the fall semester.

Poll for t-shirts: [https://forms.gle/8zDpxyxFy9URTw71A](https://forms.gle/8zDpxyxFy9URTw71A)

Things to do next:
- Plug t-shirts form more.
- Design and order t-shirt
- Order t-shirts -- with campus groups money
- Distribute t-shirts and collect money

**Comment by jrtechs** [comment]
We should post this poll in the FOSS@MAGIC socials such as their mailing list and foss.community.

**Comment by jrtechs** [comment]
put in the logo approval request for the tshirts

**Comment by jrtechs** [comment]
Sent an email to campus groups asking about the fundraising route for t-shirts. I'm also reaching out to RITAI to see what they are doing.

**Comment by jrtechs** [comment]
Alright, after talking to clubs, this is how we do this. We are going to set up a shop on campus groups for RITlug and add the t-shirt there. We will then sell the shirts there asking people for their size. At the end of the week we will use the RIT Clubs Visa card to make the purchase the t-shirts on custom ink. The funds collected through campus groups will go directly to the RITlug account so we can use this as our fundraiser for the year.

**Comment by jrtechs** [comment]
I don't think that we can technically start collecting money for this until our design request form is accepted. At the latest that should be done by Monday.

**Comment by Tjzabel** [comment]
Sounds good. I think if Tuesday comes around without a response, we should really follow up.

**Comment by nlMeminger** [comment]
campus groups store has been created for the tshirt, selling for $20

**Comment by jrtechs** [comment]
Just checked with club office, our design request has been approved, will include campus groups store in this week's email.

**Comment by jrtechs** [comment]
Just sent out a reminder email for people who have not yet went through the campus groups store.

**Comment by jrtechs** [comment]
T-shirts have been ordered and picked up. We will pass the t-shirts out this meeting(12-6). Any stragglers can be held on to over the semester or we can arrange a time for them to pick them up from me.

**Comment by jrtechs** [comment]
All t-shirts have been distributed and the money is in campus groups.
