### ISSUE TITLE
Imagine RIT 2020

### ISSUE THREAD

**Issue by jrtechs** [RITlug/tasks#133]
Proposals for Imagine RIT are due by April 1. Proposals can be submitted with [this link](https://www.rit.edu/imagine/proposals). The festival is Saturday April 25, 2020.

**Comment by Tjzabel** [comment]
A bit early for this issue :stuck_out_tongue: 

At least now we can track this.

**Comment by Tjzabel** [comment]
Imagine RIT cancelled :(
