### ISSUE TITLE
Plan/announce FOSS Family Dinner for Fall 2019 semester

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#134]
Over on the FOSSRIT side, @itprofjacobs, @ritjoe, @whenbellstoll, and I wanted to start planning for the FOSS Family dinner for this semester. Is there any thought about choosing a date/time/place for this semester?

Let me know if we can do anything to help facilitate. :slightly_smiling_face:

**Comment by itprofjacobs** [comment]
I’ll be outta town  starting 12/8

**Comment by Tjzabel** [comment]
Would Thursday, November 21st be a good date?

**Comment by jwflory** [comment]
@Tjzabel It should work for me!

**Comment by itprofjacobs** [comment]
Yep

**Comment by Tjzabel** [comment]
coral. I think the 21st is a good date. Shall we move forward with November 21st from 5:30-7pm?

**Comment by jwflory** [comment]
> Shall we move forward with November 21st from 5:30-7pm?

If it matters for a reservation, past precedent indicates a later finish time. :wink: Maybe 8:30/9pm?

**Comment by jrtechs** [comment]
@jwflory sounds good. We can discuss location tomorrow during FOSS hours.

**Comment by Tjzabel** [comment]
Sure, that works. Shouldn't be necessary to put end time on the reservation, but for creating an eventbright, it may be helpful ^.^

As another note for this year, we won't be doing any sort of fundraising activity surrounding the FOSS family dinner, so we are not time boxed.

**Comment by Tjzabel** [comment]
Set for 5:30pm - 9pm. 
Need to set an email:
* Location + Name (Bar Louie)
* Interested?
* Do yuo need a car

**Comment by jrtechs** [comment]
The interest form is live here:
https://forms.gle/Tyrdu1U53Wyay1QeA

**Comment by jrtechs** [comment]
* Just updated form so people outside of RIT can fill it out

**Comment by jwflory** [comment]
Please consider sharing on [fossrit.community](https://fossrit.community/). :slightly_smiling_face:

**Comment by jrtechs** [comment]
I can do that sometime today/tomorrow @jwflory are you going to beam this information on the FOSS mailing list?

**Comment by jwflory** [comment]
@jrtechs Anything on Discourse, I can cross-pollinate!

**Comment by jrtechs** [comment]
Just posted on the community forum

**Comment by jwflory** [comment]
Closing as complete. :smile:
