### ISSUE TITLE
Register Fall Spirit Event

### ISSUE THREAD

**Issue by jrtechs** [RITlug/tasks#135]
Register spirit event for the fall semester. 

## Background

This year all clubs have to have at least one spirit event registered. A spirit event is essentially a "more important club meeting". This year we want to have Solomon's talk count as our spirit event. Spirit events get extra visibility on campus groups.

**Comment by nlMeminger** [comment]
When have we rescheduled Solomon’s talk?

**Comment by jrtechs** [comment]
@nlMeminger his talk is currently scheduled for 11/22

**Comment by jrtechs** [comment]
https://www.rit.edu/studentgovernment/project-spirit

This^^ is the link for the current project-spirit SG initiative. I have submitted our event. I will keep this issue open until it gets approved. If this is something that SG decides to do every year, we should document this in the runbook.

**Comment by Tjzabel** [comment]
@nlMeminger all talks are available on our Fall semester schedule.

@jrtechs and cool, so you've submitted Solomon's talk as the event?

**Comment by Tjzabel** [comment]
I feel like we need to have a runbook sprint one of these days. There are a few campusgroups/club changes that have occurred the past year or so

**Comment by jrtechs** [comment]
@Tjzabel yep I submitted Solomon's talk as the event.

**Comment by jrtechs** [comment]
The event has just been approved as a spirit event
