### ISSUE TITLE
Fall 2019 Semester Retrospective

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/tasks#136]
Our last eboard meeting of the month, December 4th, is going to be our semesterly retrospective. This issue is a holding place for thoughts leading up to the meeting, meeting notes during, and possibly some thoughts/action items for the upcoming spring semester.

**Comment by jrtechs** [comment]
Start by making google form to blast out to the email to gather feedback. 
- What you liked
- What you didn't like
- What talks do you want next semester

**Comment by jrtechs** [comment]
# High-Level Plans

- Deputies for Spring Semester
- Interest form over winter break
- Advertise monthly themes as a poster so we can hang them around GCCIS.
- The email should more content about upcoming events (monthly newsletter, even high level, up next, Linux news stuff, etc)
- Do message center email for guest speakers.
- Get involved with other GCCIS clubs more so we can advertise events.

# OSSN

Hard to get our members involved in OSSN.
Nice for club management stuff.
Look into getting the larger RIT FOSS community involved in OSSN.
This might help us network more with other clubs -- promote future is open conference more. 

# Topics

- security
- Linux as a desktop (desktop environments)
- Linux as a server (cloud stuff)
- dead distros/unique/esoteric 
- do something at brick hack

# Guest Speakers

- anyone from csec
- CProffit
- mozilla -- cristos usually makes rounds in the spring
- data w/ cloud at scale 
- nolski
- red hat people in Rochester area
- Garret 
- Fedora community lead
- a person around career faire-- arrista
