### ISSUE TITLE
Reserve Spring Room (2020)

### ISSUE THREAD

**Issue by jrtechs** [RITlug/tasks#137]
Reserve the medium DB 4:30-6 on Fridays for the Spring semester of 2020.

**Comment by jrtechs** [comment]
Room is booked, we just have to add it to campus groups now.

**Comment by jrtechs** [comment]
Last week I made the request to have our meetings added to campus groups. We usually don't get these added until a week or two into the semester. I'll send an email next week if our event isn't added yet.

**Comment by Tjzabel** [comment]
Reserved :+1:

**Comment by jrtechs** [comment]
Events are in campus groups now. (for reference, that took about 12 days after submitting non-ems space request form)
