### ISSUE TITLE
Spring Semester 2020 Planning

### ISSUE THREAD

**Issue by jrtechs** [RITlug/tasks#138]
Week | Theme | Day | Title | Brief | Workshop | Presenter
-- | -- | -- | -- | -- | -- | --
1 | Distros | Jan 17 | Intro to RITlug | -- | -- | @RITlug/eboard-current 
2 | Distros | Jan 31 | Essoteric and Dead Distros | -- | --  | @hkeena98 
3 | Distros | Jan 24 | Linux Desktop Environments | -- | --  | @jrtechs @Tjzabel 
4 | Projects | Feb 7 | BrickHack Pregame | -- | --  | et. al
-- | Brick Hack | Feb 8-9 | -- | -- | --  | --
5 | Projects | Feb 14 | RITlug Lightning Talks | -- | --  | everyone
6 | Projects  | Feb 21 | Gaming on Linux | -- | --  | Dev
7 | Projects  | Feb 28 | FCAIC Guest Speaker | -- | --  | Marie 
8 | Security | Mar 6 | -- | -- | --  | Sergio Z
-- | Spring Break | -- | -- | -- | --  | --
9 | Security | Mar 20 | **[CANCELLED]** | -- | --  | @mav8557 
10 | Security | Mar 27 | **[CANCELLED]** | -- | --  | cproffit
11 | Personal Infrastructure | Apr 3 | **[CANCELLED]** | -- | --  | @nlMeminger 
12 | Personal Infrastructure | Apr 10 | **[CANCELLED]** | -- | --  | --
13 | Personal Infrastructure | Apr 17 | **[CANCELLED]** | -- | --  | --
-- | Py con | Apr 17-19 | -- | -- | --  | --
14 | Personal Infrastructure | Apr 24 | **[CANCELLED]** | -- | --  | --
-- | Imagine RIT | Apr 25 | **[CANCELLED]** | -- | --  | --
15 | -- | May 1 | no meeting finals | -- | --  | --

**Comment by hkeena98** [comment]
**Meeting Notes 1/6/2019**
General Semester Planning:
- Monthly Themes
- Distros Month (January)
- Project Month (February)
- Security Month (March)
- Personal Infrastructure Month (April)
- FOSS Meeting Times (Thursdays, 5pm - 7pm, Same Place)
- Target Goal of 1 Guest Speaker per Month
- Try to bring someone from the career fair to talk with members
- Fundraising

Guest Speakers:
- C Proffit (February)
- Datto?

First Meeting Ideas:
- Try to keep low pressure
- Project Stuff
- Quick "About Us"
- Open Floor 
- Talk about Deputy Positions
- Nathaniel will talk about Fundraising
- "Hey, come to FOSS Hours!"

Possible Talking Topics:
- Linux "Crash Course"? (Already been done, but was requested)
- Linux as a Desktop
- Linux as a Server
- Linux Distros in General
- Obscure/Dead Linux Distros (Henry)  
- Desktop Environments / Window Managers 
- Linux Security Talk with Security Club (Henry will reach out to Sean Sun)
- Differences between Desktop Management and Environments 

Projects/Project Talks:
- TigerOS, should be able to be built now
- RPM Packaging
- TeleIRC, tell people to help and learn GO

Other Notes/Points of Conversation:
- Stickers (Tim)
- iHop Dinner (Nathaniel will Call)
- OSSN Update, and future RITlug Involvement

Next Meeting Points of Interest:
- Nathaniel iHop Dinner Update

**Comment by WillNilges** [comment]
LMK if there's anything people want me to talk about in the intro presentation I'm doing.
https://docs.google.com/presentation/d/1DSGFTxLNQmGSf5GbnWE3Y8nF8zApGAj_njCm56bpt8o/edit?usp=sharing

**Comment by hkeena98** [comment]
**Meeting Notes 1/13/2019**
General Planning:
- New Cables for Servers (Tim)
- Deprecate CBet Servers (Too Old)
- Data Center Stuff
- RITlug eBoard Deputies

Talkers/Speakers:
- Possible large name people to bring in and give a talk.
- Mark Shuttleworth?
- Linus Torvalds?
- Other Large Names

First Meeting:
- eBoard Lite explanation
- Intro to RITlug
- Pitch fundraising ideas to members (sticker packs, jackets, etc.)

Fundraising:
- Custom Special Edition RITlug Stickers (Henry will ask his roommate)
- Jackets?
- Beanies?
- Nathaniel will call iHop

**Comment by hkeena98** [comment]
**Meeting Notes  1/27/2019**
General Planning:
- Deputy eBoard Members (Jake Z., Michael V)
- February 7th, BrickHack pre-event (McGregors or the like, notify members via Slack)
- Justin is coming back to campus. Give a talk? plz?
- Nathaniel will go to office to pickup club financial report

February:
- "Pre-gaming" for Brick Hack (Feb 7th)
- Lightning Talks (Feb 14th)
- Dev is giving talk about Gaming on Linux (Feb 21st)
- Guest Speaker (Feb 28th)

Fundraising:
- Nathaniel heard nothing from iHop
- Jackets, or beanies?
- Stickers (Spring 2020, Special Edition Design)

**Comment by hkeena98** [comment]
**Meeting Notes 2/3/2020**
General Planning:
- Michael Vaughan, RITSec Advertisement Plug
- Pycon (Tickets sold out in December)
- Nathaniel to go to office to get budget report
- Project/Events/Infrastructure Committees (to be renamed from "committees" to "teams")

February:
- BrickHack "pre-game" (Feb 7th)
- Lightning Talks (Feb 14th, Expected - Low Turn Out)
- Dev to give Linux Gaming Talk (Feb 21st)
- Guest Speaker (Feb 28th)

March:
- Michael to give security talk
- CProfit to give talk 

April:
- Nathaniel to give networking infrastructure talk

Fundraising:
- Nathaniel's Special "RITwug" Stickers ("Embrace, Extend, Extinguish") 
- Jackets (Estimated for $65 per jacket, estimated 12 purchases, potentially sell at cost)
- iHop is dead (issue is closed)

Projects:
- TeleIRC
- TigerOS (want to rekindle, Henry to join project team, needs advertisement for work)

**Comment by hkeena98** [comment]
**Meeting Notes 2/10/2020**
General Planning:
- Tim and Nathaniel have both missed today's meeting. This incident will be reported.
- Jeffery gave Henry & Michael the club locker combo
- Michael is going to reach out to RITSec and hopefully get a speaker for RITlug
- Jeffery explained Server Stuff
- Jeffery explained Campus Groups Email
- Figure out how to pass on the RITlug Twitter Account

March:
- CProfit to give talk, unsure of date
- Michael will give talk, unsure of date

Fundraising:
- Jackets? (We can do it)
- "RITwug" Sticker (Henry or Nathaniel will design it)

Projects:
- TeleIRC
- TigerOS

**Comment by jwflory** [comment]
The notes are super easy to follow and well-organized, thanks for this!

> Justin is coming back to campus. Give a talk? plz?

Unfortunately I leave on Thursday, so I won't be here long enough to stay for a RITlug meeting. But I am open to a remote talk. I would prefer before spring break, because I will be moving `$SOMEWHERE` and starting a new job around then.

For the Week #7 Projects slot, I could introduce the FOSS@RIT Tech Team, what projects are included in this initiative, and how to get involved.

> Figure out how to pass on the RITlug Twitter Account

There is a password for direct access, which should be documented.

However, I use Tweetdeck to manage the RITlug Twitter. It's possible to grant access to others through their personal Twitter accounts, and then you can manage it from https://tweetdeck.twitter.com. If I get a list of Twitter usernames from eboard, I can add them to the Tweetdeck shared account.

**Comment by jrtechs** [comment]
@jwflory sorry for any confusion these public notes may have caused; I'll try to catch up with you shortly in DM. Nobody on e-board as far as I'm aware of uses twitter, I was just mentioning to new Eboard members that you had ownership of the twitter and that is something we need to be aware of down the road.

**Comment by jwflory** [comment]
> Nobody on e-board as far as I'm aware of uses twitter, I was just mentioning to new Eboard members that you had ownership of the twitter and that is something we need to be aware of down the road.

No problem. Let me know if anyone needs/wants access at any point.

**Comment by Tjzabel** [comment]
## Feb 17, 2020 Notes

* April 3rd -- @nlMeminger said he can give a talk on networking
   * static IP addresses, DNS/DHCP
* Dev is good for his talk on linux gaming


March 6th:
- Mario cart party

April 24
- Lightning talks about personal infra

* @Tjzabel will work on finalizing the server cables EAF

**Comment by hkeena98** [comment]
**2/24/2020**
General Planning:
-  Nathaniel was late... by a few minutes... this incident will be reported... again...
- Removal of Sponsorship for Sticker Mule
- Find new provider of stickers
- Check to make sure that the club budget is accurate/up-to-date

February:
- Marie FCAIC Guest Speaker (Feb 28th)

March (Security Month):
- Either talk or Mario Kart on the 6th? (it was decided to go with the talk)

Imagine RIT:
- Date: April 25th
- Ordering Parts for Imagine RIT Demo

Fundraising:
- General Stickers (is there a budget for it?)
- "RITwug" Stickers (Needs improvement, Henry will create more versions)
- Look into ways to pay for the last needed fundraising (jackets, donations, etc.)
- Nathaniel to schedule appointment with office for financial review on the status of the club's budget
- Jackets, they are finally happening!

Servers:
- Tim will meet with Nathaniel about server stuff (Saturday, 29th)
- Tim to work on and finalize server cables ("I have been procrastinating so much. I don't want to deal with cables." #125 )
- "Tim, submit the damn EAF! XOXO" -Nathaniel

Projects:
- GO to be the main branch of TeleIRC soon

**Comment by hkeena98** [comment]
**Meeting Notes 3/2/2020**
General Planning:
- Tim is not at the meeting...This incident will be reported.
- Henry is too tired to function properly...
- "Tim has finally submitted the damn EAF!!!" -Nathaniel
- Jeffery got a weird email for "RITlug, the Musical"
- Server space for VMs

March:
- Sergio is giving a talk (March 6th)

April:
- "Show me what you got!" (April 17th)
- ImagineRIT (April 25th)

ImagineRIT:
- IPoS (Flag Internet Project)

Fundraising:
- "RITwug" stickers
- Jackets (Nathaniel needs to talk to Tim about Jackets)

**Comment by hkeena98** [comment]
**Meeting Notes 3/18/2020**
General Planning:
- RIT has cancelled all official meetings
- Figuring out how to deal with Novel Coronavirus Outbreak cancelling everything
- Nathaniel's microphone wasn't working. Started using his phone. This incident has been reported.
- ImagineRIT has been cancelled
- Planning for Fall semester can be supplemented with the planning from this current Spring semester
- We send out a closing email for the semester
- We are officially ending the club for the semester. We will be pointing individuals to FOSS
- Tim will clear the planning issue schedule
- eBoard meetings will continue bi-weekly for foreseeable future
- Tim explained to eBoard what the runbook is (http://runbook.ritlug.com/)
- eBoard members will assign themselves a run book issue
- Jeffery will work on the runbook website issue
- Tim and Nathaniel will work on R900 issue 
- Henry will work design approval process issue 
- Committees have been backlogged
- Add pages for teams has been backlogged
- Next eBoard meeting will take place Monday, March 30th. Following meetings will assume the biweekly meeting schedule
- Spring Semester 2020 Planning issue (#138) will remain open for the rest of the semester
- Jeffery helped Michael with Jekyll dev stuff

Eboard Nominations/Elections 2020-2021:
- eBoard 2020-2021 elections?
- Call for nominations
- Elections will follow nominations
- Henry will create re-vamped election/nominations form
- If everyone runs unopposed, then elections will be trivial

Funding/Fundraising/Spending:
- RIT has cancelled any/all future spending
- "RITwug" stickers have been postponed to fall semester
- Jackets have been postponed/cancelled indefinitely
- General Linux stickers will be moved to the fall
- Practically all funding/fundraising/buying/selling/money-related issues and topics have been either cancelled or postponed to the fall semester

**Comment by Tjzabel** [comment]
@hkeena98 thanks for the comprehensive notes!

**Comment by hkeena98** [comment]
**Meeting Notes 4/13/2020**
General Planning:
- eBoard Elections 2020-2021
- Spring Planning going forward
- eBoard faces an existential crisis and panic over the end of the semester 
- eBoard goes on a long side tracking tangent about Pennsylvania and Delaware libation laws
- Nathaniel gets angry about people using his beaches 

eBoard Elections 2020-2021:
- Henry will create a "Fair Election" poll in Campus Groups
- Henry will be new President of RITLug
- Tim will be new Vice President
- Michael will be new Treasurer
- Jeffery will be Secretary in Fall (Official Title: Officer)
- Jake will be Secretary in Spring (Official Title: Officer) 

2020-2021 Things TODO:
- Create a meme channel
- Improve the overall quality of Memes in RITLug
- Henry will officially remove Nathaniel from eBoard (...at the end of the semester...)
- Off/On boarding of old/new members of eBoard
- Club Retrospective

RITLug Website:
- Jeffery will work on website related work

**Comment by Tjzabel** [comment]
@hkeena98 updated your comment to mention that Jake will still be the official Secretary role, while Jeffery will simply be taking over for him for a semester.

**Comment by Tjzabel** [comment]
Spring semester is now complete :tada:
