### ISSUE TITLE
Eboard Transitions

### ISSUE THREAD

**Issue by jrtechs** [RITlug/tasks#145]
This issue is for documenting our eboard transitioning process.

http://runbook.ritlug.com/administration/eboard-onboarding-offboarding/#on-boarding-incoming-eboard

Tasks done:
- slack
- github
- campus groups
- google drive

TODO:
- [X] gitlab
- [X] email forwarding
- [X] telegram
- [x] slack

**Comment by Tjzabel** [comment]
@jrtechs gitlab and email forwarding is done. Unless folks already have a Telegram account, and actively use the Telegram side of the bridges, there are no permissions to update.

**Comment by Tjzabel** [comment]
Slack transitions are now complete.
