### ISSUE TITLE
Club Recognition

### ISSUE THREAD

**Issue by jrtechs** [RITlug/tasks#147]
Fill out club recognition on campus-groups. Due: June 30

Something that is new this year is that we have to list 8 members of the club other than President and Treasurer.

Also, I need to dredge up the club constitution and submit it to this form. Since the thing is latex, I'm going to try to compile it in overleaf to upload it. It might be worth it to freshen up the constitution because it may no longer be compatible with RIT club standards.

**Comment by jrtechs** [comment]
The form is submitted, I'll close this issue once it has been approved.

**Comment by Tjzabel** [comment]
Approved.
