### ISSUE TITLE
Prepare for alternative meeting methods for fall semester

### ISSUE THREAD

**Issue by jzaia18** [RITlug/tasks#148]
Prepare for fall semester in the event that club activities will be restricted to online only. This includes virtual vs irl speakers.

**Comment by Tjzabel** [comment]
We are going to run under the assumption that RITlug will need to be online for the Fall.

**Comment by jzaia18** [comment]
We are considering the possibility creating a twitch channel to stream certain parts of meetings and possibly guest speakers in the future.

**Comment by Tjzabel** [comment]
We are now hosting meetings on Discord.
