### ISSUE TITLE
Fall Semester 2020 Planning

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/tasks#149]
Week | Theme | Day | Title | Brief | Workshop | Presenter
-- | -- | -- | -- | -- | -- | --
1 | Intro Month | 8/21 | Welcome Meeting | Introduction to RITlug | No | @RITlug/eboard-current 
2 | Intro Month | 8/28 | Intro to Linux | Learn about common Linux commands | Yes | @jrtechs  
3 | Personal Infrastructure | 9/04 | Intro to Networking |  | | @nlMeminger 
4 | Personal Infrastructure | 9/11 | Personal Infra Lightning Talks | | No | @RITlug/eboard-current 
5 | Personal Infrastructure | 9/18 | Intro to LaTeX |  | N/A | @jrtechs 
6 | Personal Infrastructure | 9/25 | Alumni Panel | Open Source & Linux in the workplace |   | eboard
7 | Open Source | 10/02 | Intro to Git |  |  | @Tjzabel 
8 | Open Source | 10/09 | Strange & Esoteric Linux Distros |  |  | @hkeena98 
9 | Open Source | 10/16 | Linux terminal commands |  |  | @ Red  
10 | Open Source | 10/23 | Hacktoberfest & RITlug Projects |  |
11 | Open Source | 10/30 | Dynamic Library Interception |  |  | @mav8557 
12 | Security | 11/06 | Gemini | |  | @zethra
13 | Security | 11/13 |  |  |  | 
14 | No Meeting | Thanksgiving  |  |   |

**Comment by Tjzabel** [comment]
Possible themes: Security, Personal Infrastructure, Open Source

**Comment by jzaia18** [comment]
August (Intro):
As a potential first meeting, we're considering doing an intro as well as talking about distro hopping.
 - Idea for mock-buzzfeed quiz along the lines of "which distro are you" or "top 10 distros you wont *believe*"

For the second meeting we're considering "All about the terminal" (teaching useful and fun bash commands)
 - Activity involving SSH'ing a machine and following a maze

September (Personal Infrastructure):
We are starting to consider guest speakers; getting speakers should be easier to do as talks will be remote.
 - RITlug alumni are a safe option

**Comment by jzaia18** [comment]
Looking at doing an alumni panel around the time of career fair. Possibly around September 25th.

Considering having a meeting for "Open Source Your Resume Day" for workshopping resumes. This can include ab intro to Latex, & overleaf. A good date would be September 18th.

Should have a meeting of various small topics, such as encryption, hosting a git forge, or docker. Either the 4th or 11th.

Nathaniel will take the remaining meeting of September.

**Comment by nlMeminger** [comment]
Nathaniel will what? This is news to me.

**Comment by jrtechs** [comment]
Sorry, @nlMeminger I believe that @hkeena98 said he had reached out to you about giving the remote networking talk we planned for last spring pre-COVID. The current open meetings in September are the 4th and the 11th. If either of those dates works with you that would be amazing. We are just trying to solidify the month of September. The date that you don't take we were going to fill with an eboard medley of mini "host it yourself" talks.

**Comment by nlMeminger** [comment]
Henry Rasheed out to me last night; go ahead and put me down for the 4th
for a networking talk.

**Comment by jrtechs** [comment]
Sweet! Looking forward to the talk.

**Comment by jzaia18** [comment]
We are considering scrapping the alumni panel on the 25th in favor of Remy as a guest speaker, but this will depend on whether or not he wants to give a talk. For talks from certain speakers we might use Jitsi instead of discord, and post a link to the meeting in the discord channel.

**Comment by jzaia18** [comment]
For the lightning round infrastructure talks we have:
- Henry: Shell scripting(?), maybe dotfiles in general
- Tim: Systemd timers
- Jeffery: Hosting a gitea and reverse nginx proxy

Jeffery and Michael will split the LaTeX talk on September 18th

We plan to email the RITlug eboard alumni about giving a talk by this weekend

In October we are considering a meeting dedicated to dotfiles and configuring open source software. This might make a good first meeting for October to bridge personal infrastructure and open source.

We also considered creating a discord bot for RITlug as a Hacktoberfest project (and for utility).

**Comment by jzaia18** [comment]
Talks for October
- Intro to Hacktoberfest
- Full talk on git (maybe)
- Strange Linux distros talk
