### ISSUE TITLE
Write a blog post on TigerOS recap / overview of Flock 2018

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#15]
# Summary

Writing about TigerOS in the public is important to build awareness. We should establish a precedent for regular blog posts / updates about TigerOS.

# Description

This could be done in a few different ways.

### Our own blog

We could host our own blog, like `blog.ritlug.com`, where we could write content about the club to share with the world.

**Pros**:
* Clearly associated with RITlug
* Flexible to publish as often and as little or as much as we want

**Cons**:
* Harder to promote (starting from ground zero)
* Requires us to host more infrastructure

### Personal blogs

Team members can use their own personal blogs for updates about TigerOS.

**Pros**:
* RITlug doesn't host infrastructure
* People can write about what they're most interested in (more personal focus than team focus)
    * Ideally, more content this way!

**Cons**:
* Harder to aggregate / collect (i.e. "_Where can I keep up with TigerOS news?_")
* Possibility that someone might decide to delete their blog later / risk of lost content

### Publishing elsewhere

We could use sites like Fedora Magazine or Opensource.com to talk about the work we're doing with TigerOS.

**Pros**:
* _Much_ larger audience, better chances of being noticed
* Professional team of editors to help polish content and also promote it

**Cons**:
* Takes more time to publish content
* Writing needs to be more complete than short, tidbit updates.

# Assignees

I'm assigning this to @axk4545 primarily to take into consideration as Project Coordinator. This is important for TigerOS planning and he should discuss with the team to figure out frequency and what works best for the team.

I'm also assigned to this issue to help support and coordinate the promotion of written material on TigerOS.

**Comment by Tjzabel** [comment]
@jflory7 sounds like a great idea! Would be a good way for newcomers to glance over the changes we have made in a more readable format.

**Comment by ct-martin** [comment]
Personally I think we should have the blog on the new (WIP) TigerOS website, similar to how the RITlug one is now, except that we have a static homepage

**Comment by jflory7** [comment]
@Tjzabel Agreed. It also has the benefit of bringing more exposure for the project, which helps both the project and the people involved with it. I see this as a helpful way to grow awareness too.

@ct-martin If we did host it ourselves, we'd probably need to host it separate from the WIP project site. If we're self-hosting, I'd prefer a WordPress installation on Titan. However, I'm most in favor of the third option of publishing elsewhere.

**Comment by jflory7** [comment]
We decided to pick back up on this in the spring.

**Comment by axk4545** [comment]
FWIW I wrote one post of my own on TigerOS. It is at
https://axk4545.me/2018/03/28/TigerOS/

**Comment by jflory7** [comment]
@Tjzabel I like the idea of drafting a new article to introduce the entire project around a beta release. We should aim to publish on Opensource.com. We can use @axk4545's as a reference and revisit for any information next semester.

**Comment by jwflory** [comment]
I talked with @Tjzabel about this. We decided to make this ticket focus on writing a development update about the TigerOS recap from Flock 2018. The format will be something like a 300-500 word blog post. If possible, we can post it as a static document to our website; otherwise, we can send it as an email to our list.

The goal is to have the write-up done before the end of September. The draft can start as a shared Google Drive document.

**Comment by jwflory** [comment]
@axk4545 A guest post on my blog (or even the [Fedora Community Blog](https://communityblog.fedoraproject.org/)) isn't a bad idea (since I can cross-post it to the [Fedora Planet](http://fedoraplanet.org/)). We can review where to put it once the draft is written and we have clarification on #51.

**Comment by jrtechs** [comment]
Eboard Comment(9-10-18):
@Tjzabel is going to draft the blog post in google drive sometime in September. We will then later decide where to post it and how to send it to club members as an announcement.

**Comment by Tjzabel** [comment]
After reassessing my September schedule, it seems highly unlikely that I will be able to fully complete this task during September. I will be able to at least jot down an overview or outline, but a full essay does not seem to be in scope for this month.

**Comment by jwflory** [comment]
@Tjzabel Given the conference is in August, I think it will be harder to write the post in October. Since this issue has been open for eleven months, I am going to close it and we can re-open or file a new ticket to discuss new writing opportunities later on. Since this is your ticket, feel free to reopen it if you really do want to work on it.
