### ISSUE TITLE
2020-2021 Financial Certification

### ISSUE THREAD

**Issue by jrtechs** [RITlug/tasks#152]
Financial certifications are now live:

https://campusgroups.rit.edu/clubs/student-organization-finance/

Everyone in eboard will have to complete this quick test within a month.

**Comment by jrtechs** [comment]
Just finished

**Comment by mav8557** [comment]
You can also just click the box, apparently. I didn't know that :upside_down_face:

**Comment by Tjzabel** [comment]
Guys I did it :o
