### ISSUE TITLE
Encourage Easy & Useful Projects for Hacktoberfest

### ISSUE THREAD

**Issue by jzaia18** [RITlug/tasks#156]
# Discord Bot
* Role Assigning
* !gnulinux _let me interject_
* Sentimental rating

Written in either python or go most likely

**Comment by mav8557** [comment]
I really think this should have some kind of module system, so that people can contribute individual commands to the bot to be added in. There are a lot of other IRC bots like this, mostly Python, but I would imagine it could be done just as cleanly in Go.

**Comment by Tjzabel** [comment]
Closed due to Hacktoberfest time passing.
