### ISSUE TITLE
[DUE: OCTOBER 30] Take financial certification

### ISSUE THREAD

**Issue by jflory7** [RITlug/tasks#16]
# Summary

Club office financial certification is live. All Eboard members are required to be certified by October 30th or the club will be temporarily suspended.

# Description

The financial certification page lives here:

https://www.rit.edu/studentaffairs/campuslife/financial-certification-test

This is high priority and needs to be done in the next week. This should also be covered at the next Eboard meeting.

**Comment by jflory7** [comment]
@fosspotato Have you completed certification yet?

**Comment by jflory7** [comment]
Due to the new Eboard shuffling, only @ct-martin and @Tjzabel need to be certified. @ct-martin already took the exam. @Tjzabel is still pending.

**Comment by Tjzabel** [comment]
Has everyone here taken the financial certification? 

I am closing this issue by this time tomorrow if there are no responses.

**Comment by axk4545** [comment]
@Tjzabel I am certified

**Comment by jflory7** [comment]
@Tjzabel If you're certified now, we're all good to go. 👍
