### ISSUE TITLE
Rochester Mini Maker Faire - Nov. 18, 9am-5pm

### ISSUE THREAD

**Issue by jflory7** [RITlug/tasks#18]
# Summary

This ticket is for planning the RITlug presence at the [Rochester Mini Maker Faire](https://rochester.makerfaire.com/) (RMMF) on **Saturday, Nov. 18th from 9am to 5pm**.

# What we do

We have a table at the RMMF to display our projects and talk about club and community. People of all ages come up to talk about the things we have on our table and want to know more about them. A few volunteers at the table help introduce the projects, answer questions, and get feedback (and possibly meet new connections too).

# Attendees

We are allowed eight passes with our table. Passes get people into the Faire as an exhibitor and special access to an exhibitor's break room. The following people are joining RITlug at the RMMF:

1. Justin W. Flory (@jflory7)
2. Aidan Kahrs (@axk4545)
3. Christian Martin (@ct-martin)
4. Tim Zabel (@Tjzabel) [_12pm - 5pm_]
5. Taylor Bowling (@TaylorBowling)
6. Josh Bicking (@Josh1147582)
7. Sierra Skorupski (@sierra-skorupski)
8. 

Anyone in @RITlug/members is welcome to join and participate too.

# Inventory

We have a few supplies provided by some of our volunteers.

## @axk4545 

* (_1_) monitor
* (_2_) laptops

## @Tjzabel

* (_2_) laptops
* (_1-2_) monitors
* (_1_) USB keyboard
* (_1_) USB mouse

## @jflory7

* (_1_) laptop
* (_2_) DVI to HDMI adapters

## MAGIC

* (_X_) Raspberry Pis

# CC

@itprofjacobs @Schneidy

**Comment by Serubin** [comment]
Closed as the event has passed
