### ISSUE TITLE
Spring Semester (2018) Schedule Planning

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/tasks#19]
Week | Day | Title | Brief | Workshop | Owner
-- | -- | -- | -- | -- | --
01 | Jan. 19 | N/A |  |  |
02 | Jan. 26 | RITlug Introduction | Intro to what the club is about and who the leaders are | N/A | @Tjzabel
03 | Feb. 02 | Building a Linux Infrastructure | Using Linux to build a self-hosted infrastructure | Yes | @ct-martin   
04 | Feb. 09 | Dark Web | Intro to the Dark Web and the Tails OS | Yes | @TaylorBowling
05 | Feb. 16 | Net Neutrality | Learn all about Net Neutrality and how it affects all of us | N/A | @thenaterhood
06 | Feb. 23 | Arch & i3 | Learn how to setup Arch with this interactive meeting! | Yes  | Kyle Suero
07 | Mar. 02 | Weird and Wacky Distros | Learn about strange Linux distros | N/A | @TaylorBowling 
08 | Mar. 09 | Linux in Videogames | Learn about how Linux is involved in videogames | N/A | @TaylorBowling 
-- | Mar. 16 | _(Spring Break, no RITlug)_  | _(Spring Break, no RITlug)_  | _(Spring Break, no RITlug)_  | _(Spring Break, no RITlug)_ 
09 | Mar. 23 | Unify your music library | This hands-on workshop teaches you how to sort a music library with Picard, a tool that uses the MusicBrainz database to correct metadata in your own music. | Yes  | @jflory7
10 | Mar. 30 | TigerOS/Custom Linux Distros | Description of the TigerOS project so far | N/A | @axk4545 
11 | Apr. 06 | Swift Compiler Talk | Learn how to contribute to the Swift compiler  | N/A | @harlanhaskins 
12 | Apr. 13 | Open Source 101 | What is open source? What does it all mean and how can I get involved? A quick dive into the root of open source, finding a community, and how to get involved. | Yes | @jflory7
13 | Apr. 20 | RPM Packaging | Getting started with writing your first RPM package | Yes | @Tjzabel @axk4545 
14 | May 04 | Final Meeting | Final Meeting Game and Chill Night |No | @jflory7 @TaylorBowling

**Comment by Tjzabel** [comment]
Idea for presentation: Pinpoint -- open source presentation tool

**Comment by harlanhaskins** [comment]
Hey y'all! I'm giving a talk at [AppBuilders](https://appbuilders.ch) on April 16th, and I wanna know if y'all would be up for a practice run of my talk about how to contribute effectively to the [Swift compiler](https://github.com/apple/swift) on April 6th. (cc: @ct-martin)

**Comment by Tjzabel** [comment]
@harlanhaskins Absolutely! We'd love to have you do a talk. Shall I put you in the calendar?

**Comment by harlanhaskins** [comment]
@Tjzabel Yes, that'd be great! Sorry for missing this message.

**Comment by Tjzabel** [comment]
@harlanhaskins All good! Thanks for getting back to me. I'll add you in officially to the calendar.

**Comment by jflory7** [comment]
_Discussed in eboard meeting on 2018-02-16._

We reached out to Charles Profitt to follow-up on his availability. @Tjzabel had an idea that he could develop as a back-up option. @axk4545 also mentioned the past idea of an "open floor" or discussion night for different open source topics.

**Comment by harlanhaskins** [comment]
Hey y’all! What time of day are these meetings? I’m still committed to 4/6 but I want to make sure my co-presenter is able. If he’s not, I can present his parts.

**Comment by ct-martin** [comment]
@harlanhaskins 4-6PM (EST) in GOL/70-2620

**Comment by ct-martin** [comment]
@zedjones has interest in a talk on Godot

**Comment by zethra** [comment]
I could do a very short talk about printing with netcat.  I also have a Rust talk in the works.

**Comment by jflory7** [comment]
Hi @harlanhaskins! Could you send us an 3-4 sentence abstract of your talk to include in this upcoming week's email announcement? If you can get this to us by Sunday night, we can ship the announcement on time for Monday.

Also, if you want folks to bring a computer or have anything set up in advance, that will also be helpful to know.

**Comment by harlanhaskins** [comment]
I’ll need an HDMI cable/input, but that’s all I’ll need.

Session Description:
Swift is a landmark open-source project with hundreds of contributors and many many times more users.  The Swift community is full of intelligent, insightful users ready to contribute their voice to the project. Join Harlan and Robert, two former interns on the Swift team, on a journey from checking out source to closing a Swift bug report, live! Along the way, learn about core concepts, tips, and best practices for effectively making your mark on the Swift project.

**Comment by jflory7** [comment]
@harlanhaskins Perfect, thanks! We will have this out on Monday.

**Comment by harlanhaskins** [comment]
https://appbuilders.ch/ Is the landing page for the conference I’ll be giving this talk at, by the way.

**Comment by jflory7** [comment]
@harlanhaskins Awesome! I didn't know you were traveling for this one. We just shipped the email announcement now, so it should be propagating around. We'll try and build some awareness in other places too!

**Comment by Tjzabel** [comment]
It's a wrap! Spring semester RITlug meetings are over. Will open Fall Semester semester planning soon.
