### ISSUE TITLE
Confirm room reservation for spring semester

### ISSUE THREAD

**Issue by jflory7** [RITlug/tasks#22]
Need to confirm our room is reserved. @axk4545 will follow up John Simonson to confirm our room is reserved.

* **Room number**: GOL-2650

**Comment by ct-martin** [comment]
Still pending for eBoard and TigerOS, reopening

**Comment by ct-martin** [comment]
Everything is waiting on @axk4545 and SJ

--
Christian Martin (Phone)

**Comment by axk4545** [comment]
Waiting on SJ and IST scheduling coordinator. Requested 2620 for RITlug meetings and 2500 for eboard and TigerOS.

**Comment by axk4545** [comment]
TigerOS confirmed.

**Comment by jflory7** [comment]
@axk4545 Was GOL-2650 an option? If we can avoid moving rooms, that would be nice. We can do it if there's no other option.

**Comment by axk4545** [comment]
It was not as it is occupied by a class.


Aidan Kahrs
abkahrs@gmail.com

**Comment by jflory7** [comment]
This is also done for eboard meetings now. Starting March 2nd, we're meeting on Fridays in GOL-3455 from 2:30pm to 3:30pm.

Closing as complete. Thanks @axk4545 for following through on this.
