### ISSUE TITLE
Pre-orientation (DiscoveRIT) program for incoming class of 2018?

### ISSUE THREAD

**Issue by Chris-Bitler** [RITlug/tasks#26]
http://www.rit.edu/studentaffairs/discoverit/index.php

RIT runs a yearly pre-orientation program called DiscoveRIT the week before New Student Orientation starts. Usually this is a week-long thing to help incoming students get acquainted to the campus and to teach them about some specific subject that they are interested in. Last year, EGS did one (http://www.rit.edu/studentaffairs/discoverit/event/81) and despite having some rocky issues with RIT, it went pretty well and we helped a good number of freshman make friends before orientation and overall have a better time getting used to the campus and the area around it.

I had an idea recently that maybe RITLUG in combination with FOSS@MAGIC or something could run one this upcoming year for new students who are interested in learning more about Linux and Open Source Software. These programs generally have to do the following:

- Help incoming students learn about the campus and the majors/clubs on campus that they can be involved in
- Help incoming students learn about the Rochester area
- Help incoming students learn a bit about a specific **educational** area over the course of the week
- Help incoming students get acquainted to the campus

I helped out with EGS's thing this past year and had a great time.. maybe there is some interest in doing this but with RITLUG/FOSS@MAGIC this year?

I don't have an email on who to contact about this if there is interest, but I can ask the people in EGS who organized it who they spoke to.

**Comment by jflory7** [comment]
@Chris-Bitler Could you link us with the resources for how EGS participated? This sounds like an interesting idea.

**Comment by ct-martin** [comment]
Voted in the eboard meeting that we don't have the (human) resources to do this
