### ISSUE TITLE
Provision NextCloud VM box, work with @ct-martin on access

### ISSUE THREAD

**Issue by jflory7** [RITlug/tasks#29]
@axk4545 is working on setting up a VM in @Serubin's server for NextCloud. This unblocks @ct-martin from the NextCloud base installation.

**DUE**: 2018-02-25

**Comment by axk4545** [comment]
Currently blocked on @Serubin speaking to ITS/RIT about getting more IP addresses. Some of our current allocation has lapsed registrations.

**Comment by jflory7** [comment]
@axk4545 Does this block provisioning the machine or only offering it on a public network? If possible, it would be nice to continue setting up the box and then later make it public once the IPs are resolved.

**Comment by axk4545** [comment]
@jflory7 @ct-martin It blocks on anything beyond doing a base Ubuntu Server install. I cannot grant ssh until it can get an IP.

**Comment by Serubin** [comment]
@jflory7 No IP means no internet, unfortunately. I've been trying to get a conversation started with @n8felton without much success. I'll try and rope him in here.

**Comment by n8felton** [comment]
Oh hey, this is a thing. Whatcha need? This will probably be one of those things where you just need to nag me until it's done.

**Comment by Serubin** [comment]
Hey @n8felton, thanks for getting back to us so quick. We lost our leases on a bunch of MACs/IPs. 

First and foremost we're hoping to get some MACs registered again. I have a list of 10 which we have connected to a temp VM to keep them active on the network. Could these be registered to the RIT network, please?

```
4E:D6:15:69:55:E8
1A:11:61:75:30:36
AA:5E:CE:33:61:CB
4E:42:C1:3A:13:85
32:C6:3E:0E:C2:ED
5E:CF:3A:C8:51:94
0E:EC:F2:F7:87:9D
EE:37:D2:1D:6C:55
DA:16:2C:48:45:2D
96:0F:B6:0F:C2:FD
```

The second issue is about who the computers are registered to. Right now I own all the computers which is not ideal. I believe we have a RITLUG RIT account that they should be registered to. However, none of us have access to that account. What's the best way to get access to that account?

**Comment by cwhits** [comment]
@Serubin do you have hostnames for these or is there a specific record you want them attached to?

**Comment by Serubin** [comment]
@cwhits We've been going with x-lug.rit.edu. We're not particularly picky on host names because we end up using ritlug.com for dns.

**Comment by Serubin** [comment]
@cwhits @n8felton looks like we have access tothe ritlug user, so let's attach them to that account. I'll also post some registrations that should be transferred to that account as well.

**Comment by Serubin** [comment]
@cwhits @n8felton Any updates?

**Comment by axk4545** [comment]
We have IP addresses! Thank you @Serubin

**Comment by Serubin** [comment]
Thank @cwhits, not me!

**Comment by jflory7** [comment]
Woot, awesome! This ticket is now unblocked.

@axk4545, when do you think you can set up the VM, so we can move forward with #30? Note this is only the VM setup for this ticket.

**Comment by axk4545** [comment]
VM is setup and @ct-martin has access.

**Comment by axk4545** [comment]
DNS records also configured

**Comment by jflory7** [comment]
@axk4545 Specifically, the DNS records were `cloud.ritlug.com` and `collabora.ritlug.com`. :slightly_smiling_face:
