### ISSUE TITLE
Look into logo redesign

### ISSUE THREAD

**Issue by jflory7** [RITlug/tasks#3]
## Summary

RITlug does not have source files for our existing logo and there are a few wishes to have it redesigned into a new logo that is more modern and representative of who we are as a club. Thus, I am looking into a club logo redesign.

## Explanation

I reached out to [Ura Design](https://ura.design/) of [Opensource.com fame](https://opensource.com/article/17/6/ura-design-open-source-projects) to ask for a quote on redesigning a new logo for us. I tentatively set a design budget of this for $35.00 USD, but I think this is quite low considering what other design costs are and the quality work that Ura produces. @Serubin and I briefly discussed this at the Mozilla open source clubs event last weekend, but I'm following up on it now.

I submitted the form tonight and used the RITlug Gmail for further correspondence. Any new updates or word back from the designers will be shared here.

## Finance situation

@fosspotato At some point, I'd like to check in and get your feedback on this based on where we are with the club budget right now. This is probably part of a larger discussion we need to have about club finances anyways.

**Comment by jackrosenthal** [comment]
Gee... I already thought your logo was much better than ours. :P

**Comment by jflory7** [comment]
@jackrosenthal @jackrosenthal Heh, for me, one of the biggest reasons for this is that we don't own the original art assets, so we're just stuck to these two PNGs. Having more options would make it easier for us to produce swag or blow up our logo larger on something like a poster or something else in the future.

**Comment by jflory7** [comment]
Still waiting back from the Ura Design team, haven't had a response yet. Going to try pinging them separately if the form I submitted was received.

**Comment by jflory7** [comment]
Just as a public update, @elioqoshi from @uradesign created some first drafts of the logo. We provided some feedback and we are waiting for a final version. Hopefully we can deliver on this in early October.

**Comment by elioqoshi** [comment]
Didn't know there was an issue here. Happy to bring the conversation onto here if you have anything

**Comment by jflory7** [comment]
@elioqoshi Actually, yeah, that would be helpful! Would you mind uploading some of the mock-ups you made so far to this issue? It will be easier to get some feedback on them from others that way.

**Comment by elioqoshi** [comment]
Here we go!
![ritlug1](https://user-images.githubusercontent.com/5436686/31139516-1d03692c-a872-11e7-92f2-14452112a783.jpg)

**Comment by elioqoshi** [comment]
![ritlug2](https://user-images.githubusercontent.com/5436686/31139528-263d7ea6-a872-11e7-89ff-4c96d37f289d.jpg)

**Comment by elioqoshi** [comment]
![ritlug3](https://user-images.githubusercontent.com/5436686/31140292-48763f06-a874-11e7-8b86-b142f30b6b82.jpg)

**Comment by elioqoshi** [comment]
![ritlug4](https://user-images.githubusercontent.com/5436686/31140302-4d47e69c-a874-11e7-88d0-6bd6dc5fc90e.jpg)

**Comment by Serubin** [comment]
Adding side by side of the current contenders. Looking for feedback.
![south and west version](https://user-images.githubusercontent.com/1234465/31312836-632986d8-ab9d-11e7-81f2-f0fc97bd8c93.jpg)
Left: South Version Right: West Version

**Comment by Happy-Dude** [comment]
@Serubin I like the left one -- very penguin, very OSI :)

**Comment by elioqoshi** [comment]
With @jflory7 suggested changes

![ritlug updated](https://user-images.githubusercontent.com/5436686/31315353-5545a158-ac17-11e7-9039-fc9ab89c4181.jpg)

**Comment by jackrosenthal** [comment]
Wow these are very cool! Can't wait to see what you end up going with.

Jack

**Comment by jflory7** [comment]
We've selected final versions of the logo and updated our website, Telegram, and Slack with the new logo. Anything else with the old logo will be replaced. The new content is hosted in the site, via RITlug/ritlug.github.io#117.

I need to work with @elioqoshi on generating an invoice for the design work. I also need to clear the logo design update with club office. Keeping open until these two things are both finished.

**Comment by jflory7** [comment]
Still waiting for email with invoice from @elioqoshi.

**Comment by Serubin** [comment]
@jflory7 Status?

**Comment by jflory7** [comment]
@Serubin I have the EAF form filled out with the invoice attached. I need to wait for SJ to return from his travels to sign off on the form before I can submit it to the club office.

Since PayPal isn't an option, I'll probably pay for it out of pocket and then the university will reimburse me. It seems like for many of the things we might do, this approach is the best. But before spending funds, we'll always want to get the EAF form approved first.

It's an awful process though. I have to leave a paper copy at the desk once I have the signature, and then it will randomly appear in our club mailbox… somewhere? This has been a learning process for me…

**Comment by elioqoshi** [comment]
As said, the payment isn't a big deal for me, but if it helps you figure out what the process is like, sure :)

Hope you are all happy with the end result

**Comment by jflory7** [comment]
@elioqoshi Yes, we're getting a lot of positive feedback from others in our community about the logo redesign. This was so helpful for us, thanks again for your time! I'm hoping to have the payment processed before the new year.

**Comment by jflory7** [comment]
This was paid for this week. All logo business is wrapped up! Thanks again @elioqoshi for the great new look.
