### ISSUE TITLE
Install basic NextCloud server onto Titan VM

### ISSUE THREAD

**Issue by jflory7** [RITlug/tasks#30]
Once the VM on Titan is ready, @ct-martin will do a base install of NextCloud onto the virtual machine. After this, we are blocked on policy discussions to decide how we want to offer this service to RITlug.

* **DUE**: ~2018-04-06~ 2018-04-20

**Comment by ct-martin** [comment]
Have to push off until 4/20 due to things popping up and looking at projects due

**Comment by jflory7** [comment]
@axk4545 is going to help with this because Christian is short on bandwidth with classes. He is working on getting a bare minimum install and then we will revisit configuration at next week's eboard meeting.

**Comment by ct-martin** [comment]
Done, see #14
