### ISSUE TITLE
Complete order of new embroidered tablecloth

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#35]
@TaylorBowling is going to help us order a new tablecloth to use at events with the updated RITlug logo. The goal is to have it by Imagine RIT. We will likely use The Hub for path of least resistance.

**Comment by Tjzabel** [comment]
At the moment, it seems we will not be ordering a tablecloth _this_ semester. @TaylorBowling has mentioned he may go out and buy us a tablecloth as a donation

**Comment by Tjzabel** [comment]
## Spring 2019 Update
After a few loose discussions, I believe we have decided to go with a generic orange tablecloth. 

The goal is to have an orange tablecloth, with a new RITlug banner on the front.

**Comment by Tjzabel** [comment]
It would be nice to get a $$ update to see where we stand.

After we know how much we can work with, we can move forward with actually getting the tablecloth.

**Comment by Tjzabel** [comment]
I feel we should work on getting an embroidered tablecloth during the summer at some point. This feels like something we should have done before the fall semester starts, due to the club career fair happening right at the start of the semester.

**Comment by nlMeminger** [comment]
sent an email to the Hub to get a tablecloth printed.

**Comment by nlMeminger** [comment]
@Tjzabel do you have the SVG file we used for the banner Mark printed that had the website on it?

**Comment by jrtechs** [comment]
We will need to do a design approval request for the table cloth

**Comment by nlMeminger** [comment]
We will, which is why I want the SVG we used for the banner so that we can just reuse it and send it for approval

**Comment by jrtechs** [comment]
https://github.com/RITlug/brand/blob/master/logo/svg/horizontal_color_with_wordmark.svg

**Comment by jwflory** [comment]
> We will, which is why I want the SVG we used for the banner so that we can just reuse it and send it for approval

All the [logo SVGs are open source](https://github.com/RITlug/brand/tree/master/logo/svg) and live in [RITlug/brand](https://github.com/RITlug/brand). @nlMeminger I think you are looking for the [horizontal wordmark variant](https://github.com/RITlug/brand/blob/master/logo/svg/horizontal_color_with_wordmark.svg).

**Comment by nlMeminger** [comment]
Purchase form has been submitted and design have been submitted for approval

**Comment by jrtechs** [comment]
Sweet, just remember that we can't technically buy it until the design approval has been approved. I just sent a follow-up email to club-office about the logo approval.

**Comment by nlMeminger** [comment]
So both the purchase approval and design approval should come through at
the same time since the purchase form asked for the design since we are
using the hub

**Comment by jrtechs** [comment]
Today I picked up the tablecloth from the hub so we can use it at #129 . @nlMeminger you can close this issue after we verify that the hub correctly charged our account.

**Comment by jrtechs** [comment]
We have the tablecloth and it is looking snazzy and is currently in the club locker. According to campus groups, the hub only charged us 220 so everything looks good.

**Comment by jwflory** [comment]
Yaaaay!
