### ISSUE TITLE
Create exclusion list of VMs to not back up

### ISSUE THREAD

**Issue by jflory7** [RITlug/tasks#36]
@Serubin asked RITlug to help support the costs of backups on Titan, the primary hosted server for RITlug. We want to complete this payment by the end of this semester to effectively use the remainder of our budget.

@axk4545 and @ct-martin need to pass @Serubin a list of VMs to _not_ back up in the backup scheme. Some especially large VMs are easily reproduced with Ansible and do not contain persistent data.

Once this is done, @Serubin can work closer with us on expensing the backups and ideally paying for a long-term option with the remainder of our club budget. I chose critical priority because this is timeboxed to this semester – our budget may expire by May and we are awarded a new budget from RIT Clubs Office in the fall 2018 semester otherwise.

**Comment by jflory7** [comment]
Let's address this at the eboard meeting tomorrow.

**Comment by axk4545** [comment]
Here is what I see in Proxmox

![screenshot-2018-4-6 ritlug-titan - proxmox virtual environment](https://user-images.githubusercontent.com/3486252/38439689-9b736b38-39ac-11e8-8513-9805ca421b8f.png)

**Comment by jflory7** [comment]
@Serubin From this list that @axk4545 dug out, we can exclude 105 and 301.

I am reassigning this to you, and we can work out billing to see if we can fit it into this semester for some of 2018.

**Comment by jflory7** [comment]
I'm closing this ticket as complete. We know we don't want to back up 105 and 301. We need to process payments for backups this week if we will fit it into the budget for this semester. If we cannot get an EAF form process started, we won't be able to pay for the backups until next semester.
