### ISSUE TITLE
Plan for RITlug exhibit at Imagine RIT on Saturday, April 28

### ISSUE THREAD

**Issue by jflory7** [RITlug/tasks#38]
# Summary

Plan and organize RITlug projects to exhibit at annual [Imagine RIT](https://www.rit.edu/imagine/) festival on Saturday, April 28

# Background

RITlug is exhibiting again in the MAGIC Center for Imagine RIT. In the past, we've had a long table inside the center to exhibit various club projects. Students, alums, parents, faculty, and a few other thousand people in the Rochester community attend. This year is the tenth anniversary.

In the past, we have exhibited…

* TigerOS
* Raspberry Pi-related hardware (Minecraft, DIY projects)
* Other club member projects over the years

# Details

To successfully plan for Imagine RIT, this is a rough outline of the steps to follow:

1. Confirm list of attendees with RITlug
2. Organize and plan projects to exhibit (build inventory list of resources required)
3. Establish shifts / schedule for booth
4. Prepare printed takeaways for booth visitors

Then, exhibit!

@axk4545 is RITlug's current project coordinator and will help with organizing and mobilizing projects for Imagine RIT. @TaylorBowling also has some project ideas in mind for the table. We also have other club members planning to join us with some of their own projects.

# Outcome

An awesome booth that shows off the cool projects RITlug members are working on and provide a chance for feedback and discussion with the wider RIT community

**Comment by jflory7** [comment]
## Attendees

Currently, for Imagine RIT this year, we have this list of registered volunteers:

1. Aidan Kahrs (@axk4545)
2. Ben Goldberg (@zethra)
3. Christian Martin (@ct-martin)
4. Jeffery Russell (@jrtechs)
5. Josh Bicking (@Josh1147582)
6. Justin W. Flory (@jflory7)
7. Taylor Bowling (@TaylorBowling)
8. Tim Zabel (@Tjzabel)

More people and club members are welcome to join us, but they will not receive meal vouchers, t-shirt, or other resources provided to us by RIT that morning.

## Projects

TigerOS is obviously a major project for us to exhibit. The TigerOS team can work on the details of how they want to demonstrate and exhibit the project first (see RITlug/TigerOS#123).

@TaylorBowling also had some project ideas in mind, but we need to sync up with him in this next week once he returns from traveling.

@zethra also had an idea for exhibiting a project, but I don't have any details for that. @zethra, could you explain what you had in mind and what is needed to bring it to Imagine RIT?

Anyone else have other projects or ideas to exhibit in mind?

**Comment by axk4545** [comment]
I will be out of town that weekend. I apologize for the short notice.

**Comment by zethra** [comment]
I have a somewhat home made 3d printer I could bring in the demo.  The body of the printer is mostly made of 3d printed parts.  It's controlled by a rasbperry pi through a web interface.  I have everything I need to do the demo.  If I was going to be print stuff I'd like to be reimbursed for the filament by the club but if it's not a lot then I'm not concerned.   

I also have a piece of software that a friend of mine and I wrote that can be used for making 3d printed name tags like this.
 ![Name Tag](https://i.imgur.com/hcOHWrI.png)

**Comment by jflory7** [comment]
@zethra Cool! It would be cool if we could print some things out during Imagine. How much do you anticipate this costing? We are approaching the end of the year and our budget, so a cost estimate will help us figure out what we can cover for you.

**Comment by zethra** [comment]
Exact price depends on the filament and print size but a small name tag like the one pictured costs about 8¢ in filament

**Comment by jflory7** [comment]
@zethra Okay, cool – does a budget of $20 sound reasonable?

Also, have you already purchased the filament or is that yet to be done? I'm trying to think of the easiest way we can cover the costs for you at Imagine with RIT clubs policy.

**Comment by zethra** [comment]
@jflory7 Pricing is a bit tricky because prices and availability fluctuate.  I have two spools of filament, a green and a red, both 1kg.  The red cost me $27 and the green $23.  We could use one or both of them.  $20 would cover most of the roll.  Alternately the club could purchase it's own roll.  I typically use Hatchbox PLA. https://www.amazon.com/s/ref=nb_sb_noss_2?field-keywords=HATCHBOX+PLA

**Comment by jflory7** [comment]
@zethra I'm going to guess you don't have receipts for those two filament rolls you already purchased?

I'm thinking it will be easier to buy a new roll by RITlug with the RIT Visa card, and we can keep it for future use. Will you be at the meeting this week? We can discuss and coordinate more on making the right order then if you will be. :slightly_smiling_face:

**Comment by zethra** [comment]
I do have receipts from amazon, although the red spool has bee used a bit.  But I'd perfer the club by new ones.  I won't be at the meeting this week but I can come for few minute at the beginning.

**Comment by axk4545** [comment]
Makes sense to me but will let Justin have final say.

On Apr 10, 2018 10:00 PM, "Ben Goldberg" <notifications@github.com> wrote:

I do have receipts from amazon, although the red spool has bee used a bit.
But I'd perfer the club by new ones. I won't be at the meeting this week
but I can come for few minute at the beginning.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/RITlug/tasks/issues/38#issuecomment-380302109>, or mute
the thread

**Comment by Tjzabel** [comment]
## TIgerOS Necessities Update
The TigerOS Team has created a [list of necessities needed](https://github.com/RITlug/TigerOS/issues/123).

**Comment by ct-martin** [comment]
For records, @icflournoy will be substituting for @axk4545 who will no longer be available

**Comment by ct-martin** [comment]
@jflory7 could you please pick your desired start time and send out a calendar invite? (And document that time here)

**Comment by jflory7** [comment]
I'm trying to find the start time for the MAGIC Center this Saturday. Stay tuned.

**Comment by ct-martin** [comment]
Checklist from last week's eboard meeting notes:

## Projects
* TigerOS
* Taylor
  * Gameboy costume
* Jeffrey’s Music Player
* Ben 3D Printer
* **We need to figure out what power requirements are for each project**

Supplies:
* Tablecloth
* Monitor
* Keyboard
* Laptop
* Powerstrips - how much power?
  * Magic has a box of a lot
  * Ping Schneidy

**Comment by Tjzabel** [comment]
ImagineRIT went as planned :+1:

**Comment by jflory7** [comment]
Here's some proof that @Tjzabel wasn't lying. :smile: 

* **Twitter**: [[1](https://twitter.com/RITlug/status/990220351471869953)], [[2](https://twitter.com/KST123ABC/status/990330570231238656)], [[3](https://twitter.com/RITlug/status/990335492892889089)], [[4](https://twitter.com/RITMAGIC/status/990339153291292673)]

![RITlug table set-up / getting ready](https://user-images.githubusercontent.com/4721034/39429437-e89d70de-4c58-11e8-9f2f-66d6bad66692.png)

![RIT President Dr. Munson visits the FOSS@MAGIC and RITlug booths](https://user-images.githubusercontent.com/4721034/39429465-f5de982c-4c58-11e8-9460-42d27973f49c.png)

![Group photo of all the FOSS Folk at Imagine RIT 2018](https://user-images.githubusercontent.com/4721034/39429486-0433712c-4c59-11e8-8a1e-811cff25d0f5.png)

![Group photo of all MAGIC Center exhibitors](https://user-images.githubusercontent.com/4721034/39429510-0fe9241c-4c59-11e8-93a4-d0af94ef4064.png)
