### ISSUE TITLE
Set up relay bot from Google Group mailing list to IRC / Telegram

### ISSUE THREAD

**Issue by jflory7** [RITlug/tasks#4]
## Summary

Having a relay bot to send notifications from activity on the [ritlug-announce](https://groups.google.com/forum/#!forum/ritlug-announce) mailing list would be helpful to keep everyone updated on new announcements

## Explanation

I haven't looked into this much yet, but in theory, it should be pretty easy. We would want a relay of some kind to echo activity for new posts to our mailing list out to IRC or Telegram, so people who might be slower to check email would see a notification pop up to go read an email.

I think it might be easiest to find an IRC bot that will do this, so then the notification just echoes into Telegram. Or maybe vice versa, if there's an easier way.

**Comment by jflory7** [comment]
Umm, so I think @xforever1313 did this with xbot! I noticed it emits a notification for every new post to the mailing list. Closing as complete! Thanks @xforever1313.

**Comment by xforever1313** [comment]
Yay for accidentally fixing issues :P. I needed something to test out the Rss bot built into xbot, so I picked ritlug.com's Rss feed :P.
