### ISSUE TITLE
Financial Certification Test for Fall 2018

### ISSUE THREAD

**Issue by ct-martin** [RITlug/tasks#40]
_**Required** to use club budget_

From past precedent, it would be good to wait until fall semester before taking the test (and getting verification from club office it's up to date).

**Comment by jrtechs** [comment]
This is the link for the certification test:
[https://www.rit.edu/studentaffairs/campuslife/financial-certification-test](https://www.rit.edu/studentaffairs/campuslife/financial-certification-test)

**Comment by jwflory** [comment]
I am now financially certified. Removing myself from assignees.

**Comment by icflournoy** [comment]
I am now certified!

**Comment by ct-martin** [comment]
Done

**Comment by jrtechs** [comment]
Just got certified.

**Comment by jibby0** [comment]
I'm all certified.

**Comment by Tjzabel** [comment]
As an update, I'm currently working on this little by little

**Comment by jrtechs** [comment]
Eboard Comment(9-10-18):
Tim is still working on his financial certification.

**Comment by jwflory** [comment]
@Tjzabel Pinging for follow-up. Did you have a chance to complete this?

**Comment by Tjzabel** [comment]
@jwflory I attempted and almost completed the cert last night, but a kernel upgrade broke my computer. Will try again tonight.

**Comment by Tjzabel** [comment]
Finally got this done :+1: 

I feel my efficiency with doing this is finally improving, so that's something!

**Comment by jwflory** [comment]
@Tjzabel Yay, thanks! :tada:
