### ISSUE TITLE
Update logo and possibly link on MAGIC site

### ISSUE THREAD

**Issue by axk4545** [RITlug/tasks#45]
The [MAGIC site](https://magic.rit.edu/?page_id=1008) has our old logo under the partners and collaborators. It might be good to have this updated.

**Comment by jrtechs** [comment]
I just emailed Dr Egert (MAGIC sysadmin) about updating the logo on the MAGIC site.

**Comment by jrtechs** [comment]
Adding @ct-martin to follow up with Dr Egert since he hasn't replied.

**Comment by ct-martin** [comment]
Dr. Egert replied that he had submitted a request last time we asked and that he would follow-up with them on making sure it gets done on Tuesday

**Comment by ct-martin** [comment]
Done
