### ISSUE TITLE
Set up RITlug Namecheap account

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#47]
We need to set up a club Namecheap account to handle domain registrations and renewals. Currently, `ritlug.com` and `ritlug.club` are owned under @repkam09's personal Namecheap account. Me, @Serubin, and @ct-martin have access under our personal accounts, but for the long-term, we should move this to a club-managed account.

We can tackle this next semester.

**Comment by repkam09** [comment]
Yes! This would be good :)

**Comment by jwflory** [comment]
@repkam09 A new RITlug Namecheap account was created, username is `ritlinuxusersgroup` and the email is the RITlug Gmail. Could you try transferring the domains when you have a chance?

**Comment by jwflory** [comment]
Marking this ticket as blocked until we get a chance to follow up with @repkam09.

**Comment by repkam09** [comment]
Oh jeez! Sorry! Doing it right now!

**Comment by jwflory** [comment]
This is done. :tada: Thanks @repkam09 for transferring them over. The RITlug Namecheap account has access. Currently, me and @ct-martin have access on our personal accounts. @Tjzabel and @jrtechs should be able to log into the club account to modify settings.

Closing as complete. :clapper:
