### ISSUE TITLE
Update introduction to RITlug slides for first meeting

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#49]
In today's eboard meeting, we noted to revisit the [intro slides](https://docs.google.com/presentation/d/1q0YKfWlrdil1al5fcnCegK9oyXkS3yG7D-VEQDJ2ZRU/edit?usp=sharing) and rework the flow a little bit and add a slide or two before the first meeting. This is assigned to @Tjzabel since he is scheduled to lead this presentation in #44.

**Comment by ct-martin** [comment]
Tim will not be on campus this fall

**Comment by ct-martin** [comment]
Partly reflowed & updated to match discussion in meeting/after-meeting:
- Couple style updates to match new template
- Added "What is Linux" section (this is from after-meeting when we moved the schedule around & merged that talk into this one)
- Updated most (hopefully all) information about when/where/who
- Moved member introductions to end (based on meeting)
- Updated meeting format to closer match to what we are currently doing & wanted to do as discussed in our retrospective meeting

We still will need to do a thorough go-through closer to the date, but this takes care of the most pressing parts
- @jrtechs needs to add his photo (assigning until added)
- I want to put some of the more recent talks on the "what we do" slide
- Comments requested

**Comment by ct-martin** [comment]
Moving from "critical" to "high" - should be moved back to "critical" if we don't meet before Club Gala

**Comment by jrtechs** [comment]
@ct-martin I just added my picture to the slides.

**Comment by jwflory** [comment]
We reviewed the slides during our eboard meeting. @jrtechs and @jibby0 will pair on presenting it next Friday.
