### ISSUE TITLE
Get feedback from Eboard on task organization

### ISSUE THREAD

**Issue by jflory7** [RITlug/tasks#5]
## Summary

This repo now has various [labels](https://github.com/RITlug/tasks#labels) in use to help make it easier to sort tasks and understand what's important. Feedback is needed on whether these make sense or ways we could improve how this repo is used (so that it's easy to understand what's happening in RITlug)

## Explanation

Just now, I set up a [labeling system](https://github.com/RITlug/tasks#labels) based on a few other open source projects I spend time in. It works well for us there, but I'm curious to know what you all think about using [labels](https://github.com/RITlug/tasks/labels) and [milestones](https://github.com/RITlug/tasks/milestones) to keep track of what we're doing.

I think this is something that would benefit us working out / figuring out in person, but we can collect feedback or make improvements now since the semester is coming up pretty quickly. Ideally, I'd like to use the project boards at some point too, but we'll get there later.

Do you any of you think it would be helpful to have an informal, 15 minute how-to session on how we might want to use this repo during the semester?

**Comment by jflory7** [comment]
Per previous Eboard meeting agendas, we're going to run through a quick training on GitHub issues with @fosspotato at the next Eboard meeting, and then we will close this ticket.

**Comment by axk4545** [comment]
@jflory7 is this ok to close?

**Comment by jflory7** [comment]
@axk4545 Yes, thanks for the follow-up here. Closing this ticket.
