### ISSUE TITLE
Document CampusGroups announcements process in Runbook

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#51]
# Summary

Update [Announcements Runbook page](http://runbook.ritlug.com/en/latest/tasks/announcements.html) to offer instructions with CampusGroups mailing list

# Background

This semester, we decided to commit to using the CampusGroups mailing list. @ct-martin has used it some already for first week announcements. This decision was made to avoid emails being marked as spam.

# Details

The Runbook page should be updated to reflect best practices for sending out posts over the CampusGroups list. Instructions should include:

* How to post announcement on website
* How to access CampusGroups mailing list (any permissions needed for user account?)
* How to send mail to the list

# Outcome

Any eboard member can easily send announcement emails to the community and future eboard members will have an easier time picking up this task with no prior experience

**Comment by ct-martin** [comment]
Currently blocked on getting the Google Group to receive emails; will talk to @jwflory about during FOSS Hours

**Comment by jwflory** [comment]
Updating the priority of this ticket to critical. We need documentation on how to do this. One of us may give this a go in the next week when we send the weekly email.

**Comment by Tjzabel** [comment]
I should be able to get this done, or at least a rough draft PR done, before we need to send out this week's email.

**Comment by Tjzabel** [comment]
Okay, really this time. I _should_ be able to get this done before _this_ week's meeting :smile:

**Comment by Tjzabel** [comment]
Finally done!
