### ISSUE TITLE
Review projects introduction presentation for Sept. 14 meeting

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#52]
# Summary

Review [projects presentation](https://docs.google.com/presentation/d/1PStO5cN60xwnaNvHLE1ksmGf4u4mxxe62He9-hQ3GF0/edit#slide=id.g3fe4913624_1_66) for Sept. 14 meeting

# Background

We briefly looked over the [projects presentation](https://docs.google.com/presentation/d/1PStO5cN60xwnaNvHLE1ksmGf4u4mxxe62He9-hQ3GF0/edit#slide=id.g3fe4913624_1_66) in our eboard meeting. We wanted to have a chance to look closer at the slides and make edits / improvements to better represent some of our projects and encourage people to get involved.

# Details

I plan to review the Teleirc bits more closely.

@Tjzabel, @ct-martin, and @jibby0 will figure out how to divide and review the TigerOS slides.

We will work on other topics to include before the presentation.

# Outcome

Effective coverage about RITlug projects and encouraging new contributors to get involved with our projects

**Comment by ct-martin** [comment]
@Tjzabel will not be here to present. Would appreciate if @Tjzabel and @jibby0 would review TigerOS slides and suggest additions

**Comment by ct-martin** [comment]
Also mentioned during meeting that GitHub links should be added

**Comment by jrtechs** [comment]
# Eboard Comment(9-10-18):

## Action Item:

- We want to have final version of projects slides done by Wednesday (9-12-18).
- Open good first issues on some of our projects.
- Tim is writing draft content for email, and he will send it out over campus groups on Tuesday (9-11-18)

## Presentation:
@ct-martin: Talking about TigerOS,
@jwflory: Talking about TelaIRC.
@jrtechs: Talking about larger open source community. 
https://projects.ossn.club/
@jwflory: Personal story on how he got involved in Fedora

## Post presentation:
Break out into projects groups to help people start getting involved in our projects. We can have a telegram, TigerOS, and other groups.

**Comment by Tjzabel** [comment]
Presentation took place last Friday :+1:
