### ISSUE TITLE
Get ritlug RIT DCE account fixed

### ISSUE THREAD

**Issue by ct-martin** [RITlug/tasks#53]
It appears the `ritlug` DCE account (including ritlug@rit.edu) has been disabled - this needs to be fixed for CLAWS registration of servers & for the email forwarder (which should go to eboard@ritlug.com).

**Comment by jwflory** [comment]
@ct-martin What is the suggested action on this ticket?

**Comment by ct-martin** [comment]
Contact club office with the email in the club manual

--
Christian Martin (Phone)

**Comment by jrtechs** [comment]
I will be emailing ITS this weekend concerning the issue.

**Comment by Tjzabel** [comment]
Fixed! Me, @jwflory and @jrtechs now have access to the new password.
