### ISSUE TITLE
Integrate signin.ritlug.com with CampusGroups sign-in

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#54]
# Summary

Use CampusGroups attendance system for weekly meeting attendance tracking

# Background

This system integrates better with the system of RIT Clubs Office and helps make our club more visible inside of RIT's clubs social network. It may be helpful to show activity and engagement with our club to external actors.

# Details

@ct-martin has some ideas on this one, but wants to explore it more in depth.

# Outcome

Attendance and participation in RITlug events measured through CampusGroups

**Comment by ct-martin** [comment]
Put in the link for first meeting sign-in, will update when we figure out how the process works

**Comment by ct-martin** [comment]
Also, tried the interface with the eboard members in the meeting and it was really easy to do. Week 1 will be a trial though, and it has a manual overhead of needing the link changed ever week unless I can find a better place to link to (WIP)

**Comment by ct-martin** [comment]
The closest to a permanent link I can find is https://campusgroups.rit.edu/events?group_ids=16071
This is a major hassle to sign-in through compared to the auto-sign-in links, but it will cover more than one event. If eboard can't keep on top of updating signin.ritlug.com then that link should be used.

**Comment by jwflory** [comment]
> The closest to a permanent link I can find is https://campusgroups.rit.edu/events?group_ids=16071
>
> This is a major hassle to sign-in through compared to the auto-sign-in links, but it will cover more than one event. If eboard can't keep on top of updating signin.ritlug.com then that link should be used.

I suggest defaulting the `signin.ritlug.com` alias to this CampusGroups URL. We can make short-term short URLs with a URL shortener for individual meeting sign-ins. This ensures stable functionality with the sub-domain (lowers a possibility of something breaking suddenly for two or three eboards in the future) but also allows us to conveniently make shorter URLs for individual meetings for when we can keep on top of it.

**Comment by ct-martin** [comment]
@jwflory I would, except that the way that link does it is **extremely** circuitous and painful to do. Compared to the very painless process for the direct link, the different is huge. I will be trialling the direct link this week to see how it goes.

**Comment by ct-martin** [comment]
@jwflory another idea you had was to sent it to a Google Docs PDF, which might be do-able. I'm going to consider this issue as blocked until Friday/

**Comment by jwflory** [comment]
@ct-martin A fixed record for `signin.ritlug.com` prevents a manual task to remember each week. We should strive to automate and simplify our workflow so we can better focus on more challenging and complex tasks. I am -1 to requiring the DNS redirect for the sub-domain changed manually each week because of the high risk of it being forgotten, for both this and future eboards.

I am +0 for the idea of manually adding the PDF with QR code provided by CampusGroups to a Google Drive presentation, where `signin.ritlug.com` points to. If we decide to follow this way, Runbook documentation should be required to close this task.

I am +1 for taking the weekly attendance sign-in, manually shortening the URL, and sharing that URL at a meeting (e.g. written on a whiteboard or linked in a presentation). The level of work to do this is minimal and can also be done quickly if forgotten. It presents the least burden on current eboard and future eboards.

**Comment by jwflory** [comment]
We also need to consider the experience for eboard members to maintain the systems we create now and in the future. I suggest we put this up to vote by all eboard members at the next eboard meeting.

**Comment by jwflory** [comment]
Removing this from the meeting agenda to wait for @ct-martin to join in person for discussion.

**Comment by jwflory** [comment]
Per previous discussion, this is going to be handled in Runbook documentation (see RITlug/runbook#67). I am assigned to update this page. It's unlikely I will have it today before our eboard meeting, but I will give it another go this week when I have time.

Closing this ticket – related discussion should go to RITlug/runbook#67. :clapper:
