### ISSUE TITLE
CampusGroups welcome emails

### ISSUE THREAD

**Issue by ct-martin** [RITlug/tasks#55]
We can auto-send an email to new members when they join on CampusGroups - this would be good to have the basic info on (website, Slack, etc.)

**Comment by ct-martin** [comment]
Sent to @RITlug/eboard-current for review

**Comment by jibby0** [comment]
Looks good! Seems like a nice way to encourage new, interested members to stick around.

**Comment by ct-martin** [comment]
@jwflory also took a look, added to CampusGroups

**Comment by jwflory** [comment]
@ct-martin Could you add a screenshot here for future reference?

**Comment by ct-martin** [comment]
![image](https://user-images.githubusercontent.com/25327135/45004735-1fae5a80-afbd-11e8-8619-1eb7bcaa1a33.png)
![image](https://user-images.githubusercontent.com/25327135/45004750-36ed4800-afbd-11e8-96ff-0a0337c97088.png)
