### ISSUE TITLE
Update MAGIC Mirror

### ISSUE THREAD

**Issue by ct-martin** [RITlug/tasks#56]
Assigned to Nathaniel for Maker Faire Rochester; RITlug is storing the physical mirror but Nathaniel has the Pi to update.

**Comment by jwflory** [comment]
cc: @nlMeminger ^^

**Comment by Tjzabel** [comment]
@nlMeminger It would also be a good idea to explain what needs updating. That way we can gauge the work that has been done and see results.

**Comment by nlMeminger** [comment]
I'll have to dig into whats there before I know exactly what needs to be done to update everything, but I will update here when I have that figured out.  

From what @ct-martin was telling me about it, it just sounds like the MagicMirror software needs to be updated to the latest release, and maybe reconfigure the modules on the screen to fit.  I might also play around with adding some different modules onto the screen.

I will be using my personal MagicMirror for testing to see if it even works, but then I'll eventually grab the mirror from the club locker to do the testing with the actual screen.

**Comment by Tjzabel** [comment]
hey @nlMeminger, has there been any updates to this issue?

**Comment by Tjzabel** [comment]
@nlMeminger has updated the Magic Mirror, and there now exists a [RITlug repo](https://github.com/RITlug/MagicMirror) for the magic mirror configuration.

**Comment by Tjzabel** [comment]
@nlMeminger ping. pls

**Comment by Tjzabel** [comment]
This is complete.
