### ISSUE TITLE
Bring governance under same publishing mechanism as Runbook

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#57]
# Summary

Set up [RITlug governance documents](https://github.com/RITlug/governance) with same [Sphinx](http://www.sphinx-doc.org/)-based format with [ReadTheDocs](https://readthedocs.org/) publishing

# Background

Now that the Runbook on ReadTheDocs had its first anniversary, it has proven to be a good system for automatically creating stable, fixed documentation formats (like PDFs). It also enables us to rapidly handle contributions quickly and efficiently (and even distributed). With git tags, we can better take advantage of versioning in Sphinx to maintain different versions of our governance documents.

# Details

The first step would be to initialize a new Sphinx project in the root directory and `pandoc` all the LaTeX to reStructuredText. Once a basic site is established, we can push it (and the raw converted documents) live.

Further additions would be a content clean-up to follow our style guide and to use TravisCI to run basic tests to build the governance documents on new changes.

# Outcome

Easier for current and future eboard members to maintain club governance documents, obtain exported copies (e.g. PDF), and make revisions to the constitution without accidentally breaking the content (i.e. CI)

**Comment by Tjzabel** [comment]
I don't see this being worked on. Going to close this issue.
