### ISSUE TITLE
Follow up on November 2018 FOSS Family IHOP dinner fundraising

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/tasks#59]
This is now the prime time to start reaching out to restaurants for fall fundraisers. It would be a good idea to discuss at the next eboard meeting whether or not this is something we are interested in pursuing as an action item this fall. 

**[RSVP here!](https://www.groupraise.com/events/76016)**

**Comment by jwflory** [comment]
We briefly discussed this during FOSS Hours. @itprofjacobs suggested **Tuesday, November 27** as an ideal date to hold the dinner. It could replace FOSS Hours and we could carpool as needed from RIT.

**Comment by jwflory** [comment]
> Amaya Indian Cuisine (20%)

OMG. I didn't know they participated. I would so do that. But Indian food can be a tough option for some. :frowning_face: 

> IHop (20%)
> Outback (15%)

These two seem most viable. I am thinking IHop is better for vegetarians / diet-specific needs, plus they give us an extra 5% anyways.

**Comment by icflournoy** [comment]
### 2018-10-10 Eboard Meeting
#### Discussion
- We generally agreed that IHop is the best choice

#### Action Items
- @jibby0 will start the process to book IHop for a November 27th dinner
- Will follow up at next eboard meeting 2018-10-17

**Comment by icflournoy** [comment]
### 2018-10-17 Eboard Meeting
- IHOP is available on Nov 27th
- Estimating about 20 attendees
- **action** @jibby0 will start the GroupRaise campaign, and will send an email once its been setup
- Follow up at 10/24 eboard meeting

**Comment by jibby0** [comment]
Email has been sent, and a post has been made in #announcements.

Assuming we get at least 20 people to RSVP, we're all good for Nov 27th from 5-8pm.

**Comment by icflournoy** [comment]
### 2018-10-14 Eboard Meeting
- @jrtechs to include this in the weekly email
- waiting until we hit the 20 mininum
- sent to fossrit list (who can do this?)
- **action** @jibby0 to figure out what's involved in registering this as an off-campus event

**Comment by Tjzabel** [comment]
@icflournoy anyone who is subscribed to the FOSSRIT mailing list is able to post to it. Same as any other generic mailing list.

**Comment by jibby0** [comment]
The event has been registered as an off-campus event on https://reserve.rit.edu. Currently waiting for approval.

**Comment by icflournoy** [comment]
### 2018-10-31 Eboard Meeting
- We have 8 people confirmed going
- @jibby0 to post in #annoucements this week, next week, week leading up to the dinner
- @jibby0 will reach out to alumns / RITlug related people directly

**Comment by jwflory** [comment]
I did some 1x1 pinging this afternoon. Hoping we bring in a few more RSVPs.

**Comment by jibby0** [comment]
Update: as of today, we are still 6 people short of the 20 person deadline. A handful of FOSS friends are busy, out of town, or otherwise can't make it, sadly.

I'll do some more pinging this week. We need those 6 RSVPs by Saturday, the 24th.

**Comment by jibby0** [comment]
Our dinner was a success! We raised $74.65 for the club.

We should receive this check by early January: if we haven't heard anything by the beginning of spring semester, I'll reach out to IHOP.

**Comment by Tjzabel** [comment]
@jibby0 wondering if we should wait until Feb 1st, or send a joint email asking about both the April dinner and this one.

**Comment by jibby0** [comment]
It's been over 6 weeks (the time CampusGroups asks you to wait for the check). I'll reach out to the manager of IHOP.

**Comment by jibby0** [comment]
Heard nothing back after emailing the manager. Gonna check with club office to make sure the money didn't come in, then give the manager a call.

**Comment by Tjzabel** [comment]
@jibby0 I forget, did we get anywhere with this? IIRC we have the paper trail of this.

**Comment by jibby0** [comment]
Ah, yes. Club office didn't receive money. I'll try to give IHOP a call in the next week, to get to the bottom of things.

**Comment by Tjzabel** [comment]
It's been a solid year since this has occurred. 

@nlMeminger if you could please do an initial call to IHOP to see if they have record of RITlug doing a fundraiser here, that would be great. It would be sad to miss the $74 we raised here.

**Comment by nlMeminger** [comment]
Called IHOP and spoke with an asst manager.  Left information about the event and my contact info, and they will call me back to follow up on this

**Comment by Tjzabel** [comment]
They never followed up :(
