### ISSUE TITLE
Organize a RITlug presence at Rochester Maker Faire 2018

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#60]
# Summary

Submit a proposal to [Rochester Maker Faire](https://rochester.makerfaire.com/) for a RITlug booth and find volunteers to table with us on Saturday, November 17, 2018

# Background

Each year, RITlug attends the Rochester Maker Faire (formerly Rochester Mini Maker Faire) (see #18). We exhibit student projects and meet people from the Rochester community. It's a great outreach opportunity for RITlug and helps make our work more visible here in Rochester.

# Details

Two steps are needed for this:

- [x] [Submit proposal](https://rochester.makerfaire.com/call-for-makers/) for getting a booth
- [x] Find six to seven volunteers to help us staff the booth

## Who is coming?

- [x] @jrtechs [carpool: @jibby0]
- [x] @jibby0 [_car_]
- [x] @icflournoy [_car_]
- [x] @ct-martin [carpool: @jibby0]
- [x] @sierra-skorupski [carpool: @jibby0]
- [x] @JacobFaunce [_car_] **(noon and later)**
- [x] @KennyTaylor
- [x] @jwflory [_car_]
- [x] @nlmeminger [_car_]
- [x] Dante Paniccia

# Outcome

RITlug exhibits at the Maker Faire, we show off cool projects, we build relationships with others in the community – all-around a good time :+1:

**Comment by Tjzabel** [comment]
The [club fair runbook page](http://runbook.ritlug.com/events/club-fairs/) can be helpful for the organization aspect

**Comment by jrtechs** [comment]
# Eboard Meeting Notes 9-17-18
### Notes
- Proposal due October 15th
- 5 local eboard members are available for event @jwflory @icflournoy @ct-martin @jibby0 @jrtechs
- We should ask for more people from the club to go.
- Ideally we will have 6-8 volunteer members so people have time to talk around.

Online Proposal Contains:
-about
-what your presenting
-list of projects
-photos
-website

## Action Items

@jrtechs review exactly what form needs so next meeting we can determine what more information we need to dig up. Also, start a draft of the application -- the website allows for you to save as you go along.

**Comment by Tjzabel** [comment]
# Needed Items For Proposal
* Project Name or Title
* Full Description (Private, not published)
* Short Description (Public, for their website)
* Project Photo
* Do we have hands-on activity? If so, describe it
* "At my exhibit, you can learn how to..."
* What we need power for

**Comment by jwflory** [comment]
Marking for meeting review. The application closes in two weeks. We should make final confirmations for projects and volunteers and fill out the form.

**Comment by jrtechs** [comment]
# Eboard Meeting 10-1-18

## Discussion
We want to finalize our plan for the Rochester Maker Fair. 

## Action Items
Make a call for volunteers following Friday (10-12-18).
- Siera?
- Donte
-@jrtechs
-@jwflory 
-@icflournoy 
-@ct-martin 

Follow up with people doing projects. By this Friday (10-5-18).
@nlmeminger Mirrors
@jrtechs Musical Floppy Drives
@ct-martin Tiger OS
Dante Acoustic Levitation

After projects finalized, @jrtechs start the Maker Fair Application.

**Comment by jibby0** [comment]
> # Eboard Meeting 10-1-18
> ## Discussion
> 
> We want to finalize our plan for the Rochester Maker Fair.
> ## Action Items
> 
> Make a call for volunteers following Friday (10-12-18).
> 
>     * Siera?
> 
>     * Donte
>       -@jrtechs
>       -@jwflory
>       -@icflournoy
>       -@ct-martin
> 
> 
> Follow up with people doing projects. By this Friday (10-5-18).
> @nlMeminger Mirrors
> @jrtechs Musical Floppy Drives
> @ct-martin Tiger OS
> Dante Acoustic Levitation
> 
> After projects finalized, @jrtechs start the Maker Fair Application.

Sierra said she'd be happy to help volunteer. :+1:

**Comment by ct-martin** [comment]
FYI: @Schneidy has reminded us to get the paperwork filed soon. I sent him this issue but giving a heads up.

**Comment by ct-martin** [comment]
@jrtechs: @Schneidy has sent another reminder to submit the application. Are we reviewing the application at the meeting today or is there more action needed?

**Comment by jrtechs** [comment]
@ct-martin I have the application filled out, all that there is left to do is review the application today.

**Comment by jrtechs** [comment]
## For reference:
2017 RITlug [blurb on maker-fair website](http://rochester.makerfaire.com/maker/entry/107/)

## This year
For our public blurb I put this:
```
The RIT Linux Users Group (RITlug) is a community of students dedicated to sharing and contributing to open source projects. This year we will be showcasing four club’s projects: TigerOS, musical floppy drives, acoustic levitation, and magic mirrors.
```
Last year we didn't have any description for projects, however, this year we can't elaborate any more since we are capped at 250 characters.

**Comment by jwflory** [comment]
> For our public blurb I put this:

+1, looks good! :+1: Did you get a chance to submit it yet?

> Last year we didn't have any description for projects, however, this year we can't elaborate any more since we are capped at 250 characters.

We should make a new document in the RITlug Google Drive folder so we can recycle this text later as needed. We'll have Imagine with its application forms next semester, and our projects may only change slightly.

**Comment by icflournoy** [comment]
### 2018-10-10 Eboard Meeting

#### Discussion
- We updated the blurb in the previous comment to be consistent with the club's intro text from the website.

#### Action Items
- @icflournoy will ping Dante in slack to confirm he's demoing the acoustic levitation project on Friday
- @jrtechs will submit the application on Friday (regardless of demo)
- At the general meeting on Friday there should be a call for volunteers

**Comment by jwflory** [comment]
@jrtechs Did you get this submitted? The deadline is tomorrow, so I wanted to make sure we don't miss it.

**Comment by schneidy** [comment]
@jwflory It was submitted. I saw it come in on my end.

**Comment by jrtechs** [comment]
@jwflory yep, I submitted it on Friday. I believe I forwarded Eboard the confirmation email on Sunday.

**Comment by icflournoy** [comment]
### 2018-10-17 Eboard Meeting

- Lakka will be demoed at either this upcoming general meeting or the meeting on Nov 2nd.
- Kenneth Taylor - interested in joining RITlug at the Maker Faire. This fills our 7 spots.
- Leaving this open so we can follow up on ongoing projects.
- Magic Mirror

**Comment by jrtechs** [comment]
Today I will fill out the [Maker Agreement Form](http://rochester.makerfaire.com/wp-content/uploads/sites/25/2018/10/MFR-Maker-Agreement-2018.pdf) and upload it to the maker fair.

I will be forwarding the informative email to @RITlug/eboard-2018-2019, however, I will link the [Maker Manual](https://docs.google.com/document/d/1uLmHQolPcv2cSEtJxU1h0XS6zL6AqgyrUWO7yQyJwK0/edit) in this ticket since it is important.

**Comment by jwflory** [comment]
I bumped into @KennyTaylor the other day and he confirmed the Lakka install on the Raspberry Pi is almost done. He is planning to bring it for a demo to the meeting this Friday, Nov. 9th.

**Comment by Tjzabel** [comment]
@jwflory @jrtechs @jibby0  was a demo ever shown at the November 9th meeting?

**Comment by jwflory** [comment]
## Maker Faire day-before prep

These are the notes from our Maker Faire prep in today's general meeting.

* **ARRIVAL TIME**: 8:15 AM
* **BREAKDOWN TIME**: 5:00 PM

### Transportation

We haven't heard back from Dante yet. We are waiting to hear if he needs transportation or if he has a car.

#### @jibby0 

* @jrtechs 
* @sierra-skorupski

#### @JacobFaunce

* Kenny Taylor

#### @nlMeminger

* @ct-martin 

#### Others with cars

* @icflournoy (_off-campus_)
* @jwflory (_off-campus_)
* @itprofjacobs (_off-campus_)

### Inventory

* Monitors
  * @JacobFaunce (x2)
  * @icflournoy 
* USB controllers
  * @ct-martin 
  * @JacobFaunce
* RITlug banner: @jrtechs 
* Power strips
  * @jibby0 (+extension?)
  * @ct-martin 
* TigerOS demo laptop: @ct-martin 
* Magic Mirror: @nlMeminger
* Floppy drive music maker: @jrtechs 
* USB keyboard/mouse: @jrtechs

**Comment by Tjzabel** [comment]
Maker Faire has completed!
