### ISSUE TITLE
Review September 21st RITlug Meeting

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/tasks#62]
An email has been sent out to Mr. Mezzanini to confirm his presentation for this Friday's meetings.

The status of the presentation is currently blocked on receiving a response confirming the presentation.

We should prepare a backup presentation in the event that Mr. Mezzanini cannot make this date.

**Comment by jrtechs** [comment]
# Eboard Meeting Notes 9-17-18

If the presenter is unable to come, @ct-martin wants to do a intro to git presentation on Friday. Depending on time, @jwflory would also be able to do his open source talk which he is presenting elsewhere on Saturday.

# Action Items
@ct-martin will follow by Wednesday(9-19-18)

**Comment by ct-martin** [comment]
I have found the resources I would need to do a workshop, but don't have time to write up a complete plan today

**Comment by jwflory** [comment]
We successfully held Open Source 101 and a short session on git this past Friday. Closing as complete. :tada:  :clapper:
