### ISSUE TITLE
Discuss Long-Term Club Planning

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#63]
Notes and discussion from 2018-09-17 eboard meeting

**Comment by jwflory** [comment]
## Moving beyond small tasks

Trying to scale and grow how we work on tasks and work to help us scale out club activities and participation. Thinking of smaller tasks we discussed in today's eboard meeting. Distributed processes. Solid formatting 6-12 months ahead.

When someone goes on co-op / goes away, help promote division of responsibility and find new people to step up and lead.

## Forming sub-committees

* Events Committee
* Projects Committee
* Speaker Committee

## Suggested goal for 2018

How we scale club leadership? What happens if we lose 1-2 eboard members suddenly.

Converting RITlug eboard positions into committee heads?

## Solidifying a format for 6-12 months out

Figuring out a way to follow a consistent format for fall and spring semesters, so we can follow a "runbook" page for a semester schedule, repeat across semesters, and add new content as it comes up.

## Possible interactive sessions

* Linux installfest
* DevOps topics

Build event weeks down the road where people can get experience with different options / environments, then set up a meeting with pizza and laptops to help people get Linux installed. A division of responsibilities among eboard members.

**Comment by icflournoy** [comment]
### 2018-10-10 Eboard Meeting
@ct-martin has filed https://github.com/RITlug/tasks/issues/79 for focused discussions on the topics:
- infrastructure
- projects
- long term planning

The outcome of these meetings should feed back into the vision for the long-term club planning.

**Comment by ct-martin** [comment]
At the dedicated meeting for this we should look at the retrospective again (will post link when get a chance)

**Comment by icflournoy** [comment]
### 2018-10-14 Eboard Meeting
- Looking at scheduling this during the first weekend of November (3rd / 4th)
- Will discuss at 10/31 eboard meeting

**Comment by icflournoy** [comment]
### 2018-10-31 Eboard Meeting
- Will plan next meeting in https://github.com/RITlug/tasks/issues/79

**Comment by jwflory** [comment]
@icflournoy @jrtechs Anyone know what happened to the meeting minutes from the last special-topic eboard meeting?

**Comment by jrtechs** [comment]
@jwflory, @icflournoy documented this meeting in google docs since it was quite long. 

https://docs.google.com/document/d/1_iPkFOdyusGuVRyQuTIUTruSVeNJl0PCAjd5R9IKkvg/edit

**Comment by icflournoy** [comment]
I'll be cleaning up the doc this week now that I have some more free time.

**Comment by icflournoy** [comment]
Closing, follow up work here https://github.com/RITlug/tasks/issues/111
