### ISSUE TITLE
Organize Hacktoberfest Meetup

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/tasks#64]
### ...What is it?
For those who don't know, [Hacktoberfest](https://hacktoberfest.digitalocean.com/) is a month-long event with GitHub and DigitalOcean aimed to get more open source contributions on GitHub.

---------------

We should think about whether or not we want to have a hacktoberfest meetup at some point during October. A Saturday/Sunday hack session would be a great way to get more involvement with the club, and get to know some of the members. 

[Here](https://hacktoberfest.digitalocean.com/eventkit) is some good information DigitalOcean has laid out on how to create a Hacktoberfest meetup. 

Also, it may be a good time to use some of our Mozilla pizza money.

**Comment by ct-martin** [comment]
As a note, we have a meeting set aside for Hacktoberfest in #44 (October 5th). I second that this would be a good chance to use the pizza money. If we're looking to do something outside of a meeting, we should also consider #39 (casual coding sessions) for continuing this longer-term.

**Comment by jwflory** [comment]
Yes. I would really like to use that pizza money. :grinning:

**Comment by jwflory** [comment]
Do we want to make this part of our project collaboration night meeting this Friday?

**Comment by icflournoy** [comment]
### 2018-10-10 Eboard Meeting

#### Discussion
We are lacking the bandwidth to arrange something this weekend (13th/14th), and the following weekend is Brick City, so we are looking at October 27th/28th for a Hacktoberfest Meetup. This would lead nicely into #39 for project collaboration nights as a recurring thing throughout November/December.

We can book Javas, Artesanos, Midight Oil, Crossroads...etc.

#### Action Items
- Next eboard meeting (2018-10-17) we should decide on a date/time and a room for this Hacktoberfest meetup

**Comment by jwflory** [comment]
To clarify, this ticket is for something more than our last meeting topic? Would it be better to pilot this under project collaboration nights (#39)?

**Comment by icflournoy** [comment]
### 2018-10-17 Eboard Meeting
- Decided on a time 1-3PM @ Java's on Oct 27th
- Only @ct-martin and @jrtechs are available
- EMS event has been approved
- **action** @icflournoy will include a note in this weeks' general meeting email
- **action** @jrtechs will send a separate email next week

**Comment by icflournoy** [comment]
### 2018-10-14 Eboard Meeting
- **action** @jrtechs to mention it in this week's email
- **action** @jrtechs will post an annoucement closer to the weekend

**Comment by Tjzabel** [comment]
The hacktoberfest meeting took place last weekend. 
@jrtechs would you want to post a synopsis of what went on over the weekend as a closing remark?

**Comment by jrtechs** [comment]
We had a total of three people: myself, @ct-martin and my roommate. Low turnout was largely due to bad timing of the event since most of our eboard was out of town, it was raining, and danny hacks was going on. In the future we should send out a poll of the club to figure out when the most amount of people would be available. 

Java Wally's is a perfect location for events like these, there was plenty of space. Coffee was good :+1: 

I think that continuing this in the future would be a good idea because it would allow us to push for more projects since we would be able to sit down with people and on-board them into projects. I only say that since TigerOS is the only project with dedicated meeting time.

**Comment by Tjzabel** [comment]
@jrtechs great! This is a good baseline to go off on. Now we know how to have a good event in the future :+1:

**Comment by icflournoy** [comment]
### 2018-10-31 Eboard Meeting
_Issue resolved_
See https://github.com/RITlug/tasks/issues/39 for future collaboration events.
