### ISSUE TITLE
Review September 28th Meeting

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/tasks#66]
* [RITlug Fall Semester Schedule](https://github.com/RITlug/tasks/issues/44)

For this week's presentation, Schneidy will be guest-presenting on open hardware and the raspberry pi

**Comment by icflournoy** [comment]
### 2018-09-24 Eboard Meeting

#### Action Items
- (today) @Tjzabel will confirm with Schneidy the talk he is scheduled to give for this Friday's meeting (Sept 28th)

**Comment by Tjzabel** [comment]
Update:
Email has been sent to Schneidy for presentation confirmation

**Comment by Tjzabel** [comment]
Schneidy has confirmed he will be presenting this Friday.
