### ISSUE TITLE
Compile list of interview resources into email

### ISSUE THREAD

**Issue by icflournoy** [RITlug/tasks#69]
9/28/18's meeting showcased some useful resources to help prepare for a coding interview, general interview advice, suggested questions, etc.  It would be handy to send these resources out in an email to our members.

- https://github.com/yangshun/tech-interview-handbook
- https://exercism.io/
- https://interviewing.io/
- https://triplebyte.com/
- https://www.glassdoor.com/index.htm

**Comment by jwflory** [comment]
I just sent this email now. I also forwarded it to some other RIT lists. Closing as complete. :clapper:
