### ISSUE TITLE
Get a gigabit router/switch for CBET servers

### ISSUE THREAD

**Issue by ct-martin** [RITlug/tasks#72]
Currently the CBET servers are capable of gigabit but are on a 100Mbps switch. It would be nice to be able to use them at full capacity. At least 5 (6 if router w/ WAN port) ports, but 12+ would be nice.

**Comment by jwflory** [comment]
@ct-martin I don't know much about good hardware for this. Could you suggest two or three options and how much they cost so we can plan accordingly with our budget (especially as we are getting ready to follow up on our budget allocation from Clubs Office soon in #67).

**Comment by Tjzabel** [comment]
With all this being said, I'm assuming there's no way to have these servers connect to the RIT network via already available equipment without needing to buy new equipment?

**Comment by ct-martin** [comment]
@jwflory
https://www.amazon.com/NETGEAR-16-Port-Gigabit-Ethernet-Unmanaged/dp/B01AX8XHRQ/
https://www.amazon.com/TRENDnet-Unmanaged-Forwarding-Protection-TEG-S16DG/dp/B0044GJ516/

@Tjzabel there is one drop-down cable and we have a 100Mbps switch, but there are 5 gigabit-capable servers with 2 NICs each, so there's a definite limiting factor

**Comment by jwflory** [comment]
@ct-martin Thanks for the links. Assuming we spend a minimum of $50 USD, this exhausts 20% of our (current) budget for this academic year.

What are we currently using the machines for that requires an upgraded data link?

I suggest we block this ticket by #67. If we receive a notable increase in budget from Club Office based on the case we present, I am more ready to experiment and try something new. If we do not receive a budget increase, I think we should revisit since this purchase is 20% of our budget until May. It could strap us thin for purchases made for the Maker Faire, Imagine, and other costs that arise during this and the next semester.

**Comment by icflournoy** [comment]
I'm going to take a look at hardware that I have laying around. I know I have a 24+ port gigabit switch, and it's very possible I have something that can act as a gigabit edge router.

I'll compile a list of a few things I'd be willing to donate for the club's benefit.

**Comment by icflournoy** [comment]
@ct-martin The switch is a `Nortel BayStack 5510-48T` which is a 48 port gig switch. I have two (not sure where the other one is).  I will donate it to the club if you think it can be used.

Its got a serial interface for initial configuration. I should have the cable somewhere around here to interface with it.

**Front of switch**
![img_20181014_153932 1](https://user-images.githubusercontent.com/1166328/46921385-91b88d00-cfc8-11e8-9294-fa0abd051183.jpg)

**Comment by icflournoy** [comment]
I've also got
- Cisco ASA 5510 (rackmount security device)
- Cisco ASA 5505 (smaller form factor, built in 100MB switch with 8 ports or so)

The 5510 supports gig on both sides and could be useful as an edge device.

**Comment by icflournoy** [comment]
### 2018-10-14 Eboard Meeting
@jrtechs @ct-martin @icflournoy are headed to the datacenter on 10/15 to install a router/switch to get external access to the machines

**Comment by Tjzabel** [comment]
@ct-martin @icflournoy Is this issue taken care of? As far as I can tell, @icflournoy has donated his switch to us to use with the CBET servers.

**Comment by icflournoy** [comment]
### 2018-10-31 Eboard Meeting
- Switch is in club possession in the club locker.
_issue resolved_
