### ISSUE TITLE
Regain control of RITlug IFTTT account

### ISSUE THREAD

**Issue by ct-martin** [RITlug/tasks#75]
Currently no one on eboard knows the credentials or email (for password reset) being used for IFTTT, which has hooks for production RITlug things, such as the mailing list.

**Comment by jwflory** [comment]
This is completed by [eboard/credentials#4](https://git.ritlug.com/eboard/credentials/merge_requests/4) in our GitLab. Turns out it was programmed to our RITlug Gmail after all.

Closing as complete. :clapper:
