### ISSUE TITLE
Add GitHub root password to private repo

### ISSUE THREAD

**Issue by ct-martin** [RITlug/tasks#77]
@jwflory

**Comment by Tjzabel** [comment]
I *believe* this is needed to keep uniformity when we create a RITlug GitLab user?

**Comment by ct-martin** [comment]
@Tjzabel it's primarily so that as project members come and go the OAuth tokens won't expire

Also because it's important to have there.

**Comment by jwflory** [comment]
Added in [eboard/credentials#5](https://git.ritlug.com/eboard/credentials/merge_requests/5). Closing as complete. :clapper:
