### ISSUE TITLE
Verify domain at GitHub org level

### ISSUE THREAD

**Issue by ct-martin** [RITlug/tasks#82]
https://help.github.com/articles/verifying-your-organization-s-domain/

**Comment by jwflory** [comment]
@ct-martin Nice, I didn't hear about this. I added the TXT records to both ritlug.com and ritlug.club. The domain verification is pending in our GitHub organization now. It may take 72 hours to propagate.

**Comment by ct-martin** [comment]
It appears it didn't go through in the end, I will poke when I have time for ritlug.com

**Comment by ct-martin** [comment]
(it's under 72 hours, but the page has steps and it looks like it got checked too early)

**Comment by ct-martin** [comment]
Fixed a typo in the record, now waiting on Namecheap Standard Propagation Timeline of eventually maybe. Also figured out how the verification actually works for my reference.

**Comment by icflournoy** [comment]
### 2018-10-17 Eboard Meeting
- Continuing to wait for propagation, will revisit at 10/24 eboard meeting

**Comment by ct-martin** [comment]
Restarted process. Turns out that Namecheap's panel made it unclear in adding the subdomain so my fix to Flory's entry was just as wrong. Currently waiting for it to propagate correctly if it ever does.

**Comment by ct-martin** [comment]
FYI, the command to check if it's there is `dig @dns1.registrar-servers.com _github-challenge-ritlug.ritlug.com +nostats +nocomments +nocmd -t txt` and you should see a 10-digit code in a record

**Comment by ct-martin** [comment]
ritlug.com is verified, need to verify gmail.com or change the email to a ritlug.com one in order to complete this. Also, ritlug.club is not verified due to me not having access under my personal account and it being too late at night for me to feel like checking if it's under the club account.

**Comment by ct-martin** [comment]
Also, the GitHub backend is being a bit flacky, the domain might show as not verified but I confirmed it is (if you try to re-do the process it tells you you already did it).

**Comment by ct-martin** [comment]
Updated the email, we are now verified
![image](https://user-images.githubusercontent.com/25327135/47302100-a3b0b600-d5ee-11e8-8ab9-07590363a900.png)

**Comment by ct-martin** [comment]
Oh, got ritlug.club verified too
