### ISSUE TITLE
Work with Mark to print a new RITlug banner

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#86]
@repkam09 offered to help print a free 24x36" color poster (the benefits of knowing people at Kodak). :smile: To help Mark with this, we should create a poster design or have some loose idea of what we want to include on the poster.

**Comment by jwflory** [comment]
@repkam09 Is it enough to just send you the logo we want printed? Or do we need to send a PDF / other design to make this happen?

Just sending the logo is most convenient for us since it's already ready, but we can probably get a more print-friendly format together if necessary.

**Comment by jwflory** [comment]
@repkam09 I think this is probably the logo we would want to print, and I think it would be enough as-is. The rest of @RITlug/eboard-current could leave feedback on logo preference too.

Would you be able to use this logo?

[![RITlug horizontal color logo with wordmark](https://user-images.githubusercontent.com/4721034/48595424-8f788400-e922-11e8-8c7a-8d766322afe5.png)](https://github.com/RITlug/brand/blob/master/logo/svg/horizontal_color_with_wordmark.svg "RITlug horizontal color logo with wordmark")

**Comment by Tjzabel** [comment]
@jwflory what is the purpose of printing out our logo on a poster? Is this more for a banner?

**Comment by ct-martin** [comment]
@Tjzabel yes, it's a banner. The current one uses the old logo and is generally dated

**Comment by Tjzabel** [comment]
@repkam09 ping

**Comment by Tjzabel** [comment]
@repkam09 hey mark! Just wondering if this is still something you can do?

**Comment by icflournoy** [comment]
Reminder: upload the non-svg version of the banner, so that fonts are rendered.

**Comment by Tjzabel** [comment]
I've confirmed with @repkam09 that the banner has been printed! I will most further updates once more is known.

**Comment by Tjzabel** [comment]
This is finally complete! Thanks @repkam09 :tada: :tada:
