### ISSUE TITLE
Plan next CBET trip #4

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#88]
@ct-martin did some work with the CBET servers in #76. He wants to coordinate another visit with Dr. Skuse in the near future.

**Comment by Tjzabel** [comment]
To maintain a more organized approach to these CBET trips, I would like to have a comment added in here as to what goal we hope to achieve from each trip.

**Comment by ct-martin** [comment]
Next trip will be to pull out the non-working servers down there, and if possible, get them registered on the RIT network properly (which blocks on #85). Also rumor from a person that we may see a donation of a server sometime in the near-ish future, which I'd put down if we get it before this trip. In all likelihood, this trip might not happen until next semester.

**Comment by ct-martin** [comment]
We might get the server donation tomorrow (will find out by mid-day), and the servers needing work will be pulled from CBET on 11/6

**Comment by jwflory** [comment]
@ct-martin Is the server donation something we should document? I think I remember you looked into this a while back about donations but not sure where that discussion went.

**Comment by ct-martin** [comment]
@jwflory we should document (and in a different issue). I don't remember if/what club office needs to know about this, although I know we discussed it a couple times. @jibby0 do you remember?

**Comment by ct-martin** [comment]
Servers were pulled out and put in the Lab for Data Acquisition & Analytics and I was granted swipe access. I was also told a couple days ago that the other server donation was dropped off over break, but I won't be able to look at it until I get back. I have a computer I'm going to donate as well which is about the same-ish power as the old server we have, but newer hardware. Closing this issue as completed, continuation will go in another issue.
