### ISSUE TITLE
Install TigerOS on demo laptop for Maker Faire

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/tasks#89]
We need to have TigerOS set for the Maker Faire.

@ct-martin said he would take charge to attempt the impossible task of installing TigerOS onto Aidan's laptop, which seemingly refuses to install from USB.

**Comment by ct-martin** [comment]
It does install from USB, but only certain ones. I have a couple magic drives that work.

**Comment by Tjzabel** [comment]
As a very small update to this issue, we have a mostly-working F29 TigerOS ISO that can be used for a Maker Faire demo.

**Comment by ct-martin** [comment]
This is definitely going to be something I don't get to until the meeting on Friday

**Comment by Tjzabel** [comment]
@ct-martin :+1:

**Comment by Tjzabel** [comment]
Since Maker Faire kinda happened today, I think it's safe to close this issue :)
