### ISSUE TITLE
Planning for 2171 club fair (Saturday, August 28th, 2017)

### ISSUE THREAD

**Issue by jflory7** [RITlug/tasks#9]
## Summary

The RIT club fair is coming up – RITlug has a table, and we need to plan out who will be there, when they will be there, and maybe any strategy that we want to try different for this year

## Raw details

* **Date**: Saturday, August 28th, 2017
* **Volunteers needed**: 12:00pm - 4:30pm
  * **Event times**: 1:00pm - 4:00pm
* **Table**: C8

## Who's going to be there

* @jflory7 (12:00pm - 4:30pm)
* @axk4545 (???)

## Inventory

* @Serubin:
  * [?] Eboard t-shirts
* @TaylorBowling:
  * RITlug club poster

## Execution

Okay, so this is coming up super fast! This is probably one of our highest priority tickets. I know @Serubin and @TaylorBowling have already said they will not be available on these dates, so I've tentatively assigned it to me, @axk4545, and @fosspotato until someone tells me otherwise. 😁 

**One of the biggest priorities is that we need to figure out inventory.** I remember there was a hand-off on our poster between @wilfriedE and @Serubin, but I lost track of what happened with this and where our poster is. @Serubin also has the Eboard t-shirts, but I forgot how many of them. Other than that, I'd like to try to have two laptops / monitors at the club fair for us to put up our website and maybe have a TigerOS demo running, if that is possible. Also, a tablecloth of any kind would be nice to have this year, since last year, we winged it at the last minute.

@schneidy also has shared that he might have some content we can share or talk about with regards to the FOSS program, which I would love to do. I'm tagging him here so he can hopefully clarify on anything that he can pass along that we can share. 😄 

I also want to put a call out to any RITlug members who happen to be in Rochester that they can help out and volunteer with this. I wouldn't say no to anyone wanting to spend a little bit of time table-sitting with us and saying hello to all of the freshman. Even if it's just 30 minutes, it would be super nice to have so that way people can take lunch / bathroom breaks without doing a mad dash back.

## Checklist

This is a long issue. So here's a checklist. I like checklists.

* [x] Locate missing club poster
* [ ] Coordinate shipping of Eboard shirts to Rochester
* [ ] Round up volunteers to help operate the table
* [ ] Coordinate with @schneidy on distributing FOSS@MAGIC materials
* [ ] Obtain / purchase a tablecloth of some kind
* [x] Find two laptops to volunteer as tribute
  * [x] _BONUS_: Find a monitor so we can use the laptops at the table _at the same time_

I might have missed something, but we can amend this later.

**Comment by axk4545** [comment]
@RITlug/eboard-2017-2018 I have a 1280x1024 vga monitor that we can use and a chromebook that can be one of the laptops.

**Comment by jflory7** [comment]
@axk4545 If you could commit those for the club fair, that would be awesome. What's running on the Chromebook right now?

**Comment by axk4545** [comment]
@jflory7 ChromeOS but it can run any x86 linux we want. It has 2GB RAM.

**Comment by jflory7** [comment]
@axk4545 Do you think a Cinnamon install would keep up? It would be cool to do Fedora Cinnamon or Mint, if you think it could cope with that. Ideally, just any kind of Linux would be nice, where people can open a browser or a terminal and poke around.

**Comment by axk4545** [comment]
@jflory7 it can run TigerOS so yes.

**Comment by jflory7** [comment]
@axk4545 Awesome. Then if you can work on getting a TigerOS install running on that before the club fair, that would be super cool. It would make for a good talking point at the table too if we had that running. 😄

**Comment by axk4545** [comment]
@jflory7 will try to get TigerOS cleaned up to do that. Buggest thing is F26 move and hopefully fixing that silly autostart.

**Comment by Tjzabel** [comment]
@axk4545 I thought we fixed the autostart??

**Comment by axk4545** [comment]
@Tjzabel Well we kinda did... it still tries to run on the live CD AFAIK

**Comment by wilfriedE** [comment]
@jflory7 I gave the RITLUG poster to @Serubin. I think that was the only thing?

**Comment by Serubin** [comment]
@jflory7 @wilfriedE It's with @TaylorBowling

**Comment by jflory7** [comment]
@Serubin How many t-shirts do we have? Do you want to ship them to my home address in Georgia so I can bring them with me to ROC?

**Comment by jflory7** [comment]
Sorry for the double-comment, but @TaylorBowling, will you be able to get the poster to someone before Aug. 28th?

**Comment by jflory7** [comment]
So, this did indeed happen, and it went well. Sorry for the delayed follow-up here. I don't have much to add, but a quick overview of things that went well and things that could have been better:

# Success

* @Schneidy's Cre8-a-thon posters drew in a lot of people, the art + hacking idea seemed to resonate with a lot of people
* Talking with people specific to their interests and was able to connect them to things beyond just Linux happening in the club
* Had a good elevator pitch for the club (would be good to get something like that written down / documented, maybe in RITlug/runbook?)
* More well-prepared than last year: tablecloth was a good investment

# Improvements

* More monitors would have been helpful, especially with dedicated keyboard + mouse for people to enter form (has to swivel laptops back and forth when one machine was slow / had lots of people filling out form)
* Printed takeaways would be helpful (posters / info cards about RITlug with key info, like website + meeting place and times)
* On-site mailing list sign-up
* Doing a dry run right before – i.e. when we go to set up, are we sure this is going to work? (network cut out on one machine during the fair)
* If budget allows, getting a dedicated tablecloth with logo
