### ISSUE TITLE
Define guidelines for meeting presenters

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#90]
From 2018-11-07 eboard meeting. Next steps are to define set of guidelines for meeting presenters (esp. around communication / empathy). I'm collecting a loose set of guidelines and I'll share them in this issue before the next eboard meeting on 2018-11-14.

**Comment by jwflory** [comment]
As a next step for this ticket, I suggest we implement the [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct) as a code of conduct for presentations and interactions inside of RITlug physical and virtual spaces. It would supplement [RIT's Code of Conduct](https://www.rit.edu/academicaffairs/policiesmanual/d180).

The Contributor Covenant says all the things I would want to tell guest speakers about our expectations too, specifically this section:

![Excerpt: "Our Standards" from Contributor Covenant](https://user-images.githubusercontent.com/4721034/48959627-aaf01a00-ef34-11e8-9d6a-2923e53aa6dc.png "Excerpt: 'Our Standards' from Contributor Covenant")

The next step for us is to decide if we want to implement this code of conduct globally in all club spaces (meetings, presentations, Slack, Telegram groups, etc.) or only for presentations. It's also worth considering the level of commitment this decision requires. See "[_Linux kernel hastily adopts standard Code of Conduct_](https://otter.technology/blog/2018/09/20/linux-kernel-hastily-adopts-standard-code-of-conduct/)" for an example of implementing a code of conduct without additional planning.

Tagging for discussion at next eboard meeting.

**Comment by icflournoy** [comment]
### 2018-11-28 Eboard Meeting Notes

Start by applying a document like the Contributor Covenant to RITlug speakers/presenters.

Speak with SJ about the pragmatics of enforcement:
- What would implementing/enforcing during a meeting (outside of presentations) look like in practice?
- What would we do in the face of a presenter violating a code of conduct? How is our feedback delivered to the presenter?
- Have two points of contact (eboard, SJ)

In the future we would expand the scope of the code of conduct to other discourse happening in the club.

@jrtechs and @jwflory Will discuss with SJ on December 4th, Tuesday, FOSS Hours.

**Comment by jrtechs** [comment]
@jwflory and myself were unable to chat with SJ about this on the 4th because SJ had to leave Foss hours early.

I believe that we should try to reschedule that meeting; however, doing so may be difficult since it near the end of the semester. 

Personally, I don't think that it would be a bad idea to start rolling out a basic [code of conduct](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/) to some of our major git repositories. That way we have something to start with. But, that would require us to decide on a code of conduct.

**Comment by jwflory** [comment]
@jrtechs Yeah, last night ended up being a little hectic. I think it's a good idea to bring this up with @itprofjacobs either over email during the break or right at the start of next semester. We can mark it as blocked for now.

**Comment by Tjzabel** [comment]
Guidelines have been discussed for new meeting presenters. Each presenter will be briefed on proper meeting etiquette.
