### ISSUE TITLE
Secure room reservation for spring semester

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/tasks#92]
We currently don't have a room reservation for the spring semester. We need to contact RIT about this soon.

**Comment by jrtechs** [comment]
Once we do the reservation for the spring semester we should address run book issue ritlug/runbook#49 
I can take on the task of updating the run book documentation for this over winter break.

**Comment by jrtechs** [comment]
I can confirm that we have the room reserved for our weekly meetings in the large DB. Now, we just have to add the events to campus groups.

**Comment by ct-martin** [comment]
@jrtechs we need to make sure it gets approved by club office, we've had issues with that in the past

**Comment by Tjzabel** [comment]
Club meetings show up in CampusGroups now.

Closing issue.
