### ISSUE TITLE
Off-board Justin from RITlug eboard

### ISSUE THREAD

**Issue by jwflory** [RITlug/tasks#93]
At the end of the semester, we should follow [standard off-boarding procedure](http://runbook.ritlug.com/administration/eboard-onboarding-offboarding/) for me from RITlug eboard.

**Comment by Tjzabel** [comment]
I veto this idea.

**Comment by jrtechs** [comment]
I can work with @Tjzabel over winter break to do this. 

Have we ever done anything with the [email aliases](http://runbook.ritlug.com/administration/eboard-onboarding-offboarding/)? I think I should update this page over Christmas break -- we still have references to Facebook on this page.

**Comment by ct-martin** [comment]
TigerOS uses tigeros@ when interacting with upstream, and I would like to
keep tigeros-lead@ and projects@ around because they're useful on occasion

--
Christian Martin (Phone)

**Comment by jwflory** [comment]
@ct-martin Sounds good. I opened #95 to keep track of documenting that.

**Comment by jwflory** [comment]
I completed my off-boarding tasks this morning. I have done the following:

* De-listed as officer in CampusGroups
* Removed from eboard email alias
* Removed from _Current Eboard_ GitHub organization team
* Removed from Google Drive folder

My Slack membership needs to be downgraded from an owner to a member (I think only @Tjzabel can do this as primary owner). I will also leave the eboard private group soon.

**Comment by Tjzabel** [comment]
As a follow-through, Just has been downgraded successfully from Workplace Owner to Full Member status.

**Comment by ct-martin** [comment]
@jwflory was still a GitHub Org owner and was on the TigerOS Admins team. I have made him a regular member and removed him from the admins group. As a note, in the future we should keep these issues open until a remaining eboard member has verified that all off-boarding has been completed.

**Comment by ct-martin** [comment]
Found another to do (@Tjzabel): remove @jwflory from the RITlug private GitLab repos

**Comment by Tjzabel** [comment]
:wave: @jwflory
