### ISSUE TITLE
Look at moving all infrastructure-related issues to RITlug/Infrastructure

### ISSUE THREAD

**Issue by Tjzabel** [RITlug/tasks#94]
It may be a good idea to look at consolidating all issues related to the RITlug infrastructure to the [RITlug Infrastructure](https://github.com/RITlug/infrastructure) repository.

That way, we can get good use out of the repo, and all infra-related issues can be hosted in one central location.

**Comment by jrtechs** [comment]
@Tjzabel Do you want to migrate all current infrastructure related issues out of tasks and into the infrastructure repository?

**Comment by Tjzabel** [comment]
@jrtechs I agree with what @jwflory said. Infra-specific tasks would be great to migrate over. Tasks that involve eboard participation should stay in the tasks repo. 

This would allow infra-related issues to move at their own pace, and gives them a place to be congregated.

**Comment by ct-martin** [comment]
If you move tickets I would appreciate if you copied over the history as I've left notes in some of the issues. Otherwise, do as you wish I guess. Please tag me on any issues I should be tagged on in the new repo so I get the emails

**Comment by Tjzabel** [comment]
@ct-martin this isn't a "do as you wish" sort of thing. The Infrastructure repo will host other things not related to current infra tickets. If you would like, we can move *future* infrastructure tickets to the repo.

**Comment by jwflory** [comment]
On a side note, if we do want to migrate existing tickets later, this feature was introduced a month or two back if you noticed it in the sidebar of issues:

![Transfer a GitHub issue to another repository](https://user-images.githubusercontent.com/4721034/49835999-14fb2280-fd6f-11e8-9036-39b8f19e81c4.png "Transfer a GitHub issue to another repository")

I've transferred issues across repos elsewhere and it worked well for a beta feature. This bridge can be crossed once it arrives. :slightly_smiling_face:

**Comment by ct-martin** [comment]
I transferred a bunch of issues to the infra repo and re-added the meta-issues on the ops project board.

Note for future reference: if you transfer issues, the labels, project boards, milestones, & references to the issue (such as #xx) get broken.
