### ISSUE TITLE
Spring Semester (2019) Planning

### ISSUE THREAD

**Issue by jrtechs** [RITlug/tasks#96]
Week | Theme | Day | Title | Brief | Workshop | Owner
-- | -- | -- | -- | -- | -- | --
1 | First Meeting | Jan 18 | OS Installfest | Welcome to the Spring Semester! This meeting focuses on an overview of Linux distributions followed by an installfest | Yes | @Tjzabel et. al
2 | Linux | Jan 25 | `systemd` | Learn why systemd is cool! | N/A | Garrett
3 | Cloud | Feb 1 | Intro to "The Cloud" | Learn all about "the Cloud!" | N/A | @icflournoy @ct-martin 
4 | Cloud | Feb 8 | Kubernetes | Ever wondered how to auto-scale applications? Come to this meeting to find out! | N/A | @Tjzabel 
5 | Cloud | Feb 15 | Open (Floor) Cloud Platform | Series of Lightning talks on personal experiences using the cloud | N/A | @icflournoy 
6 | Cloud | Feb 22 | Intro to Ansible | Learn about Ansible | N/A | @jwflory 
7 | Up and Coming Tech | Mar 1 | Graph DB | Come learn how graph databases will change your life! | -- | @jrtechs 
8 | Up and Coming Tech | Mar 8 | ZFS And Filesystems | Come learn all about ZFS and other filesystem differences! | N/A | @jibby0 
-- | | Spring break | -- | -- | -- | --
9  | Programming | Mar 22 | Rust Language | Come learn all about the Rust language! | Yes | @zethra 
10 | Programming | Mar 29 | Programming Languages Speed Talks | Conglomeration of different programming languages | -- | --
11| Maker movement | Apr 5 | Building a website with Jekyll | Has "make a (better?) portfolio/personal website" been on your to-do list for months? If so, this workshop is for you! | Yes | @ct-martin
12 | Maker movement | Apr 12 | Linux Workflows |  |  | @RITlug/eboard-current  
13 | Maker movement | Apr 19 | State of FOSS tools in Design & Creativity | -- | -- | @ct-martin
14 | Maker movement| Apr 26 | Pre-ImagineRIT | Last minute prep and demos of ImagineRIT projects | -- | @jrtechs 
-- | -- | Apr 27 | ImagineRIT | -- | -- | --
Finals

**Comment by icflournoy** [comment]
### Eboard Meeting Notes 2019-01-17

1/18 - This Friday's Install-fest:
- break into four corners
- assist with downloading ISOs and loading them onto a virtual machine
- Supply a few flash drives for the people who want to install on their machine
- have some OpenBSD, Project Trident
- Jason with NixOS

1/25 - systemd with Garret:
- What is systemd, features (dependencies, targets, timers)
- When is it used for
- Systemd service accounting (network, cpu, memory, io) @icflournoy can provide more insight here
- Demo? Making a systemd service, or timer
- Journald demo, finding logs, tailing
- Interaction between systemd and selinux @tjzabel

@icflournoy will talk to Garret by 1/22 (Tuesday) about what we want to show off

February **Cloud**:
- Intro to Cloud and Security Considerations. XaaS - Looking at the OSI model and finding cloud component equivalencies. @icflournoy and @ct-martin presenting.
- Ansible Automation @jwflory 
- Software Defined Networking (@ct-martin knows someone who may present on Ceph, etc)
- Kubernetes demo with @tjzabel

March **Up and Coming Technologues**:
- Matrix, Decentralization @jibby0
- Graph Databases @jrtechs

**Comment by zethra** [comment]
I would like to give a talk on the Rust programming language.

**Comment by Tjzabel** [comment]
@zethra great! Does either March 22 or March 29 work for you to fit in with our Programming theme?

**Comment by zethra** [comment]
Either should work.

**Comment by Tjzabel** [comment]
@zethra great! I put you in for March 22. When the time comes closer (or if you know now), let me know if you would like this talk to be interactive / have a workshop. 

Also, let me know if you would like to change the *Title* or *Brief*.

**Comment by ct-martin** [comment]
@icflournoy how does this sound for the intro/sec cloud talk?

> Come learn about the layers that make up "The Cloud" & the security concerns at each of those layers.

**Comment by jibby0** [comment]
Would anyone be interested in a talk on ZFS for Up and Coming Tech?

Could throw some other interesting/new/experimental filesystems in there too (btrfs, maybe even ReFS and AppleFS), how they compare to the oldies (FAT) and common journaled filesystems (NTFS, ext4, etc.). Or make it a general FS talk. I don't think we've had one of those since Nate Levesque's.

**Comment by Tjzabel** [comment]
@jibby0 I would be interested!

**Comment by jibby0** [comment]
@Tjzabel Cool! I'd be happy to do that on March 8th then. :smile:

**Comment by ct-martin** [comment]
Note to self: multiple requests for a Jekyll/Build-A-Website workshop. I might be able to do this in April

**Comment by Tjzabel** [comment]
Potential idea for April 26th: mini-presentations on projects we are presenting at imagineRIT the next day on the 27th.

**Comment by ct-martin** [comment]
I have written in the following talks/workshops for April:

Apr 5: Building a website in Jekyll (cc @nlMeminger, @jwflory )
Apr 12: FOSS in Interactives
Apr 19: State of FOSS tools in Design & Creativity
Apr 26: ImagineRIT prep/demos

cc @RITlug/eboard-current

**Comment by jrtechs** [comment]
Spring semester meetings are finally over. I would like to thank everyone who presented at the club this semester.
