### ISSUE TITLE
Decide Spring 2019 monthly topics

### ISSUE THREAD

**Issue by ct-martin** [RITlug/tasks#98]
We have the following topics, we need 2-3 sentences & a couple bullet points of sub-topics. _(This is from Long-Term Planning Meeting (#63); I have added a picture of the whiteboard to the GDoc)_

Topics and who will do the write-up:
* Cloud (Ian)
* Security (Tim)
* Maker movement (Christian)
* Up and Coming Technologies (Jeffery)
* Programming (Josh)

**Comment by jrtechs** [comment]
Up and Coming Technologies: 

> Learn about the cool new technologies that are shaping the Open Source community today.
> Topics:
> - Big Data
> - Open Data
> - Graph Databases
> - Machine Learning
> - Decentralization

With this topic we can possibly have some interesting talks about open source metrics and data visualization.

**Comment by icflournoy** [comment]
Cloud
> Put your head in the clouds and discover what's behind the scenes at major cloud providers.
> - Linux in the Cloud
> - Automation
> - Cloud Security
> - Software Defined Networking
> - Block Storage

Programming
> What can you do when you combine software and hardware?
> - Controlling GPIO on a Raspberry Pi
> - Esoteric Programming Languages
